<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.jdragon.studio</groupId>
        <artifactId>data-aggregation-studio-backend</artifactId>
        <version>0.1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>studio-flink</artifactId>
    <name>studio-flink</name>

    <dependencies>
        <dependency>
            <groupId>com.jdragon.studio</groupId>
            <artifactId>studio-commons</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.jdragon.studio</groupId>
            <artifactId>studio-dto</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.jdragon.studio</groupId>
            <artifactId>studio-infra</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.jdragon.studio</groupId>
            <artifactId>studio-nacos-compat-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.jdragon.aggregation</groupId>
            <artifactId>commons</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jdragon.aggregation</groupId>
            <artifactId>data-source-handler-abstract</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jdragon.aggregation</groupId>
            <artifactId>plugins-loader-center</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.16.1</version>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-runtime</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-clients</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-api-java-bridge</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-api-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-runtime</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-planner_2.12</artifactId>
        </dependency>
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>janino</artifactId>
        </dependency>
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>commons-compiler</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>remove-bundled-source-plugin-runtime</id>
                        <phase>process-resources</phase>
                        <configuration>
                            <target>
                                <delete dir="${project.build.outputDirectory}/dataaggregation-plugin-runtime"/>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.jdragon.studio.flink.bootstrap.StudioFlinkApplication</mainClass>
                    <classifier>exec</classifier>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>flink-connector-bundle</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>3.2.2</version>
                        <executions>
                            <execution>
                                <id>connector-jar</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <classifier>connector</classifier>
                                    <includes>
                                        <include>com/jdragon/studio/flink/connector/**</include>
                                        <include>META-INF/services/org.apache.flink.table.factories.Factory</include>
                                        <include>dataaggregation-plugin-runtime/**</include>
                                    </includes>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.1.0</version>
                        <executions>
                            <execution>
                                <id>bundle-source-plugin-runtime</id>
                                <phase>prepare-package</phase>
                                <configuration>
                                    <target>
                                        <mkdir dir="${project.build.outputDirectory}/dataaggregation-plugin-runtime/conf"/>
                                        <echo file="${project.build.outputDirectory}/dataaggregation-plugin-runtime/conf/core.json"><![CDATA[{"core":{"plugin":{"reporter":[]}}}]]></echo>
                                        <macrodef name="bundle-source-plugin">
                                            <attribute name="module"/>
                                            <attribute name="plugin"/>
                                            <sequential>
                                                <mkdir dir="${project.build.outputDirectory}/dataaggregation-plugin-runtime/plugin/source/@{plugin}"/>
                                                <unzip src="${project.basedir}/../../../data-source-plugins/@{module}/target/@{plugin}.zip"
                                                       dest="${project.build.outputDirectory}/dataaggregation-plugin-runtime/plugin/source/@{plugin}"/>
                                            </sequential>
                                        </macrodef>
                                        <bundle-source-plugin module="data-source-handler-dm" plugin="dm"/>
                                        <bundle-source-plugin module="data-source-handler-file-ftp" plugin="ftp"/>
                                        <bundle-source-plugin module="data-source-handler-file-s3-minio" plugin="minio"/>
                                        <bundle-source-plugin module="data-source-handler-file-sftp" plugin="sftp"/>
                                        <bundle-source-plugin module="data-source-handler-http" plugin="http"/>
                                        <bundle-source-plugin module="data-source-handler-file-tbds-hdfs" plugin="tbds-hdfs"/>
                                        <bundle-source-plugin module="data-source-handler-file-tbds-hdfs3" plugin="tbds-hdfs3"/>
                                        <bundle-source-plugin module="data-source-handler-influxdb" plugin="influxdb"/>
                                        <bundle-source-plugin module="data-source-handler-influxdbv1" plugin="influxdbv1"/>
                                        <bundle-source-plugin module="data-source-handler-mysql5" plugin="mysql5"/>
                                        <bundle-source-plugin module="data-source-handler-mysql8" plugin="mysql8"/>
                                        <bundle-source-plugin module="data-source-handler-odps" plugin="odps"/>
                                        <bundle-source-plugin module="data-source-handler-oracle" plugin="oracle"/>
                                        <bundle-source-plugin module="data-source-handler-postgres" plugin="postgres"/>
                                        <bundle-source-plugin module="data-source-handler-queue-kafka" plugin="kafka"/>
                                        <bundle-source-plugin module="data-source-handler-queue-rabbitmq" plugin="rabbitmq"/>
                                        <bundle-source-plugin module="data-source-handler-queue-rocketmq" plugin="rocketmq"/>
                                        <bundle-source-plugin module="data-source-handler-tbds-hive2" plugin="tbds-hive2"/>
                                        <bundle-source-plugin module="data-source-handler-tbds-hive3" plugin="tbds-hive3"/>
                                    </target>
                                </configuration>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <artifactId>maven-shade-plugin</artifactId>
                        <version>3.3.0</version>
                        <executions>
                            <execution>
                                <id>connector-upload-jar</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>shade</goal>
                                </goals>
                                <configuration>
                                    <shadedArtifactAttached>true</shadedArtifactAttached>
                                    <shadedClassifierName>connector-upload</shadedClassifierName>
                                    <createDependencyReducedPom>false</createDependencyReducedPom>
                                    <artifactSet>
                                        <includes>
                                            <include>com.jdragon.aggregation:commons</include>
                                            <include>com.jdragon.aggregation:data-source-handler-abstract</include>
                                            <include>com.jdragon.aggregation:plugins-loader-center</include>
                                            <include>commons-configuration:commons-configuration</include>
                                            <include>commons-io:commons-io</include>
                                            <include>commons-lang:commons-lang</include>
                                            <include>commons-logging:commons-logging</include>
                                            <include>com.alibaba:fastjson</include>
                                            <include>com.alibaba.fastjson2:fastjson2</include>
                                            <include>com.alibaba.fastjson2:fastjson2-extension</include>
                                            <include>com.fasterxml.jackson.core:jackson-annotations</include>
                                            <include>com.fasterxml.jackson.core:jackson-core</include>
                                            <include>com.fasterxml.jackson.core:jackson-databind</include>
                                        </includes>
                                    </artifactSet>
                                    <filters>
                                        <filter>
                                            <artifact>com.jdragon.studio:studio-flink</artifact>
                                            <includes>
                                                <include>com/jdragon/studio/flink/connector/**</include>
                                                <include>META-INF/services/org.apache.flink.table.factories.Factory</include>
                                                <include>dataaggregation-plugin-runtime/**</include>
                                            </includes>
                                        </filter>
                                        <filter>
                                            <artifact>*:*</artifact>
                                            <excludes>
                                                <exclude>META-INF/*.SF</exclude>
                                                <exclude>META-INF/*.DSA</exclude>
                                                <exclude>META-INF/*.RSA</exclude>
                                            </excludes>
                                        </filter>
                                    </filters>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
