CREATE TABLE `meta_field_definition` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT 'default',
  `deleted` int DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `schema_version_id` bigint DEFAULT NULL,
  `field_key` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `field_name` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `description` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `scope` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `value_type` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `component_type` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `required_flag` int DEFAULT '0',
  `sensitive_flag` int DEFAULT '0',
  `sort_order` int DEFAULT '0',
  `validation_rule` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `placeholder` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `default_value` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `options` json DEFAULT NULL,
  `searchable_flag` int DEFAULT '0',
  `sortable_flag` int DEFAULT '0',
  `query_operators` json DEFAULT NULL,
  `query_default_operator` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci