CREATE TABLE `run_record` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT 'default',
  `deleted` int DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `workflow_definition_id` bigint DEFAULT NULL,
  `workflow_version_id` bigint DEFAULT NULL,
  `node_code` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `status` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `worker_code` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `message` varchar(2000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `ended_at` datetime DEFAULT NULL,
  `payload_json` json DEFAULT NULL,
  `result_json` json DEFAULT NULL,
  `execution_type` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `collection_task_id` bigint DEFAULT NULL,
  `log_file_path` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `log_size_bytes` bigint DEFAULT NULL,
  `log_charset` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `workflow_run_id` bigint DEFAULT NULL,
  `project_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_run_record_project_created` (`project_id`,`created_at`),
  KEY `idx_run_record_project_workflow_run` (`project_id`,`workflow_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci