create table if not exists model_sync_task (
  id bigint primary key,
  tenant_id varchar(64) default 'default',
  project_id bigint,
  deleted int default 0,
  created_at datetime default current_timestamp,
  updated_at datetime default current_timestamp,
  datasource_id bigint not null,
  datasource_type varchar(128),
  datasource_name_snapshot varchar(255),
  batch_no int not null,
  name varchar(255),
  source varchar(64),
  status varchar(64),
  total_count int default 0,
  success_count int default 0,
  failed_count int default 0,
  stopped_count int default 0,
  progress_percent int default 0,
  stop_requested int default 0,
  created_by bigint,
  started_at datetime,
  finished_at datetime,
  duration_ms bigint,
  last_error varchar(1000),
  unique key uk_model_sync_task_project_datasource_batch (project_id, datasource_id, batch_no),
  key idx_model_sync_task_project_created (project_id, created_at),
  key idx_model_sync_task_project_status (project_id, status)
);
