CREATE TABLE `data_model_attr_index` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(64) COLLATE utf8mb4_general_ci DEFAULT 'default',
  `deleted` int DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `model_id` bigint DEFAULT NULL,
  `datasource_id` bigint DEFAULT NULL,
  `meta_schema_version_id` bigint DEFAULT NULL,
  `meta_schema_code` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `scope` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `meta_model_code` varchar(128) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `item_key` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `field_key` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `value_type` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `keyword_value` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `text_value` text COLLATE utf8mb4_general_ci,
  `number_value` decimal(38,10) DEFAULT NULL,
  `bool_value` int DEFAULT NULL,
  `raw_value` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`),
  KEY `idx_model_attr_index_model` (`model_id`),
  KEY `idx_model_attr_index_datasource` (`datasource_id`),
  KEY `idx_model_attr_index_lookup` (`meta_schema_code`(128),`scope`,`field_key`(128),`keyword_value`(128)),
  KEY `idx_model_attr_index_number` (`meta_schema_code`,`scope`,`field_key`,`number_value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci