package com.jdragon.studio.infra.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.jdragon.studio.dto.model.DataServiceApiMetricView;
import com.jdragon.studio.dto.model.DataServiceMetricDistributionView;
import com.jdragon.studio.infra.entity.DataServiceAccessLogEntity;
import com.jdragon.studio.infra.model.OpenServiceDashboardBucketSummary;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;

import java.time.LocalDateTime;
import java.util.List;

@Mapper
public interface DataServiceAccessLogMapper extends BaseMapper<DataServiceAccessLogEntity> {

    @Delete("delete from data_service_access_log where occurred_at < #{before}")
    int purgeBefore(@Param("before") LocalDateTime before);

    @SelectProvider(type = OpenServiceMetricSqlProvider.class, method = "selectDataServiceDashboardSummary")
    DataServiceApiMetricView selectDashboardSummary(@Param("tenantId") String tenantId,
                                                    @Param("projectId") Long projectId,
                                                    @Param("serviceIds") List<Long> serviceIds,
                                                    @Param("requestedClusterId") Long requestedClusterId,
                                                    @Param("actualClusterId") Long actualClusterId,
                                                    @Param("subscriptionId") Long subscriptionId,
                                                    @Param("noTokenSubscription") boolean noTokenSubscription,
                                                    @Param("success") Integer success,
                                                    @Param("cacheHit") Integer cacheHit,
                                                    @Param("logFocus") String logFocus,
                                                    @Param("minDurationMs") Long minDurationMs,
                                                    @Param("startTime") LocalDateTime startTime,
                                                    @Param("endTime") LocalDateTime endTime,
                                                    @Param("hourGranularity") boolean hourGranularity);

    @SelectProvider(type = OpenServiceMetricSqlProvider.class, method = "selectDataServiceDashboardBuckets")
    List<OpenServiceDashboardBucketSummary> selectDashboardBuckets(@Param("tenantId") String tenantId,
                                                                   @Param("projectId") Long projectId,
                                                                   @Param("serviceIds") List<Long> serviceIds,
                                                                   @Param("requestedClusterId") Long requestedClusterId,
                                                                   @Param("actualClusterId") Long actualClusterId,
                                                                   @Param("subscriptionId") Long subscriptionId,
                                                                   @Param("noTokenSubscription") boolean noTokenSubscription,
                                                                   @Param("success") Integer success,
                                                                   @Param("cacheHit") Integer cacheHit,
                                                                   @Param("logFocus") String logFocus,
                                                                   @Param("minDurationMs") Long minDurationMs,
                                                                   @Param("startTime") LocalDateTime startTime,
                                                                   @Param("endTime") LocalDateTime endTime,
                                                                   @Param("hourGranularity") boolean hourGranularity);

    @SelectProvider(type = OpenServiceMetricSqlProvider.class, method = "selectDataServiceDashboardErrorDistribution")
    List<DataServiceMetricDistributionView> selectDashboardErrorDistribution(@Param("tenantId") String tenantId,
                                                                             @Param("projectId") Long projectId,
                                                                             @Param("serviceIds") List<Long> serviceIds,
                                                                             @Param("requestedClusterId") Long requestedClusterId,
                                                                             @Param("actualClusterId") Long actualClusterId,
                                                                             @Param("subscriptionId") Long subscriptionId,
                                                                             @Param("noTokenSubscription") boolean noTokenSubscription,
                                                                             @Param("success") Integer success,
                                                                             @Param("cacheHit") Integer cacheHit,
                                                                             @Param("logFocus") String logFocus,
                                                                             @Param("minDurationMs") Long minDurationMs,
                                                                             @Param("startTime") LocalDateTime startTime,
                                                                             @Param("endTime") LocalDateTime endTime,
                                                                             @Param("hourGranularity") boolean hourGranularity,
                                                                             @Param("limit") int limit);

    @SelectProvider(type = OpenServiceMetricSqlProvider.class, method = "selectDataServiceDashboardApiStats")
    List<DataServiceApiMetricView> selectDashboardApiStats(@Param("tenantId") String tenantId,
                                                           @Param("projectId") Long projectId,
                                                           @Param("serviceIds") List<Long> serviceIds,
                                                           @Param("requestedClusterId") Long requestedClusterId,
                                                           @Param("actualClusterId") Long actualClusterId,
                                                           @Param("subscriptionId") Long subscriptionId,
                                                           @Param("noTokenSubscription") boolean noTokenSubscription,
                                                           @Param("success") Integer success,
                                                           @Param("cacheHit") Integer cacheHit,
                                                           @Param("logFocus") String logFocus,
                                                           @Param("minDurationMs") Long minDurationMs,
                                                           @Param("startTime") LocalDateTime startTime,
                                                           @Param("endTime") LocalDateTime endTime,
                                                           @Param("hourGranularity") boolean hourGranularity,
                                                           @Param("orderMode") String orderMode,
                                                           @Param("limit") int limit);

    @SelectProvider(type = OpenServiceMetricSqlProvider.class, method = "selectDataServiceDashboardSubscriptionRank")
    List<DataServiceApiMetricView> selectDashboardSubscriptionRank(@Param("tenantId") String tenantId,
                                                                   @Param("projectId") Long projectId,
                                                                   @Param("serviceIds") List<Long> serviceIds,
                                                                   @Param("requestedClusterId") Long requestedClusterId,
                                                                   @Param("actualClusterId") Long actualClusterId,
                                                                   @Param("subscriptionId") Long subscriptionId,
                                                                   @Param("noTokenSubscription") boolean noTokenSubscription,
                                                                   @Param("success") Integer success,
                                                                   @Param("cacheHit") Integer cacheHit,
                                                                   @Param("logFocus") String logFocus,
                                                                   @Param("minDurationMs") Long minDurationMs,
                                                                   @Param("startTime") LocalDateTime startTime,
                                                                   @Param("endTime") LocalDateTime endTime,
                                                                   @Param("hourGranularity") boolean hourGranularity,
                                                                   @Param("limit") int limit);

    @Select({"<script>",
            "select count(1)",
            "from (",
            "  select service_id",
            "  from data_service_access_log",
            "  where deleted = 0",
            "    and tenant_id = #{tenantId}",
            "    and project_id = #{projectId}",
            "    <if test='requestedClusterId != null'>and requested_cluster_id = #{requestedClusterId}</if>",
            "    <if test='actualClusterId != null'>and actual_cluster_id = #{actualClusterId}</if>",
            "    and service_id is not null",
            "    and occurred_at &gt;= #{startTime}",
            "    and occurred_at &lt;= #{endTime}",
            "    <choose>",
            "      <when test='serviceIds != null and serviceIds.size() &gt; 0'>",
            "        and service_id in",
            "        <foreach collection='serviceIds' item='serviceId' open='(' separator=',' close=')'>#{serviceId}</foreach>",
            "      </when>",
            "      <otherwise>and 1 = 0</otherwise>",
            "    </choose>",
            "    <if test='subscriptionId != null'>and subscription_id = #{subscriptionId}</if>",
            "    <if test='noTokenSubscription'>and subscription_id is null</if>",
            "    <if test='success != null'>and success = #{success}</if>",
            "    <if test='cacheHit != null'>and cache_enabled = 1 and cache_hit = #{cacheHit}</if>",
            "    <if test='logFocus == \"ERROR\"'>and success &lt;&gt; 1</if>",
            "    <if test='logFocus == \"SLOW\"'>and duration_ms &gt;= #{minDurationMs}</if>",
            "    <if test='logFocus == \"ERROR_OR_SLOW\"'>and (success &lt;&gt; 1 or duration_ms &gt;= #{minDurationMs})</if>",
            "  group by service_id",
            ") grouped",
            "</script>"})
    long countApiStats(@Param("tenantId") String tenantId,
                       @Param("projectId") Long projectId,
                       @Param("serviceIds") List<Long> serviceIds,
                       @Param("requestedClusterId") Long requestedClusterId,
                       @Param("actualClusterId") Long actualClusterId,
                       @Param("subscriptionId") Long subscriptionId,
                       @Param("noTokenSubscription") boolean noTokenSubscription,
                       @Param("success") Integer success,
                       @Param("cacheHit") Integer cacheHit,
                       @Param("logFocus") String logFocus,
                       @Param("minDurationMs") Long minDurationMs,
                       @Param("startTime") LocalDateTime startTime,
                       @Param("endTime") LocalDateTime endTime);

    @Select({"<script>",
            "with filtered as (",
            "  select",
            "    id, service_id, occurred_at, coalesce(duration_ms, 0) as duration_ms, success, cache_enabled, cache_hit, row_count",
            "  from data_service_access_log",
            "  where deleted = 0",
            "    and tenant_id = #{tenantId}",
            "    and project_id = #{projectId}",
            "    <if test='requestedClusterId != null'>and requested_cluster_id = #{requestedClusterId}</if>",
            "    <if test='actualClusterId != null'>and actual_cluster_id = #{actualClusterId}</if>",
            "    and service_id is not null",
            "    and occurred_at &gt;= #{startTime}",
            "    and occurred_at &lt;= #{endTime}",
            "    <choose>",
            "      <when test='serviceIds != null and serviceIds.size() &gt; 0'>",
            "        and service_id in",
            "        <foreach collection='serviceIds' item='serviceId' open='(' separator=',' close=')'>#{serviceId}</foreach>",
            "      </when>",
            "      <otherwise>and 1 = 0</otherwise>",
            "    </choose>",
            "    <if test='subscriptionId != null'>and subscription_id = #{subscriptionId}</if>",
            "    <if test='noTokenSubscription'>and subscription_id is null</if>",
            "    <if test='success != null'>and success = #{success}</if>",
            "    <if test='cacheHit != null'>and cache_enabled = 1 and cache_hit = #{cacheHit}</if>",
            "    <if test='logFocus == \"ERROR\"'>and success &lt;&gt; 1</if>",
            "    <if test='logFocus == \"SLOW\"'>and duration_ms &gt;= #{minDurationMs}</if>",
            "    <if test='logFocus == \"ERROR_OR_SLOW\"'>and (success &lt;&gt; 1 or duration_ms &gt;= #{minDurationMs})</if>",
            "),",
            "grouped as (",
            "  select",
            "    service_id,",
            "    count(1) as access_count,",
            "    coalesce(sum(case when success = 1 then 1 else 0 end), 0) as success_count,",
            "    coalesce(sum(case when success = 1 then 0 else 1 end), 0) as failure_count,",
            "    coalesce(min(duration_ms), 0) as min_response_time_ms,",
            "    coalesce(max(duration_ms), 0) as max_response_time_ms,",
            "    coalesce(round(avg(duration_ms)), 0) as avg_response_time_ms,",
            "    max(occurred_at) as last_access_at,",
            "    coalesce(sum(case when cache_enabled = 1 then 1 else 0 end), 0) as cache_enabled_count,",
            "    coalesce(sum(case when cache_enabled = 1 and cache_hit = 1 then 1 else 0 end), 0) as cache_hit_count,",
            "    coalesce(sum(case when cache_enabled = 1 and cache_hit &lt;&gt; 1 then 1 else 0 end), 0) as cache_miss_count,",
            "    coalesce(sum(case when cache_enabled &lt;&gt; 1 or cache_enabled is null then 1 else 0 end), 0) as cache_disabled_count",
            "  from filtered",
            "  group by service_id",
            "),",
            "ranked as (",
            "  select",
            "    service_id,",
            "    duration_ms,",
            "    row_number() over (partition by service_id order by duration_ms asc, id asc) as rn,",
            "    count(1) over (partition by service_id) as cnt",
            "  from filtered",
            "),",
            "percentiles as (",
            "  select",
            "    service_id,",
            "    coalesce(max(case when rn = ceiling(cnt * 0.95) then duration_ms end), 0) as p95_response_time_ms,",
            "    coalesce(max(case when rn = ceiling(cnt * 0.99) then duration_ms end), 0) as p99_response_time_ms",
            "  from ranked",
            "  group by service_id",
            ")",
            "select",
            "  g.service_id as service_id,",
            "  g.access_count as access_count,",
            "  g.success_count as success_count,",
            "  g.failure_count as failure_count,",
            "  g.min_response_time_ms as min_response_time_ms,",
            "  g.max_response_time_ms as max_response_time_ms,",
            "  g.avg_response_time_ms as avg_response_time_ms,",
            "  coalesce(p.p95_response_time_ms, 0) as p95_response_time_ms,",
            "  coalesce(p.p99_response_time_ms, 0) as p99_response_time_ms,",
            "  g.last_access_at as last_access_at,",
            "  g.cache_enabled_count as cache_enabled_count,",
            "  g.cache_hit_count as cache_hit_count,",
            "  g.cache_miss_count as cache_miss_count,",
            "  g.cache_disabled_count as cache_disabled_count",
            "from grouped g",
            "left join percentiles p on p.service_id = g.service_id",
            "order by g.access_count desc, g.last_access_at desc",
            "limit #{limit} offset #{offset}",
            "</script>"})
    List<DataServiceApiMetricView> selectApiStatsPage(@Param("tenantId") String tenantId,
                                                      @Param("projectId") Long projectId,
                                                      @Param("serviceIds") List<Long> serviceIds,
                                                      @Param("requestedClusterId") Long requestedClusterId,
                                                      @Param("actualClusterId") Long actualClusterId,
                                                      @Param("subscriptionId") Long subscriptionId,
                                                      @Param("noTokenSubscription") boolean noTokenSubscription,
                                                      @Param("success") Integer success,
                                                      @Param("cacheHit") Integer cacheHit,
                                                      @Param("logFocus") String logFocus,
                                                      @Param("minDurationMs") Long minDurationMs,
                                                      @Param("startTime") LocalDateTime startTime,
                                                      @Param("endTime") LocalDateTime endTime,
                                                      @Param("limit") int limit,
                                                      @Param("offset") int offset);
}
