package com.jdragon.studio.infra.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.jdragon.studio.dto.model.DataIngestionApiMetricView;
import com.jdragon.studio.dto.model.DataServiceMetricDistributionView;
import com.jdragon.studio.infra.entity.DataIngestionAccessLogEntity;
import com.jdragon.studio.infra.model.OpenServiceDashboardBucketSummary;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;

import java.time.LocalDateTime;
import java.util.List;

@Mapper
public interface DataIngestionAccessLogMapper extends BaseMapper<DataIngestionAccessLogEntity> {

    @Select({"<script>",
            "select id, updated_at, request_id, log_storage_type, log_object_bucket, log_object_key, log_charset, log_archive_status",
            "from data_ingestion_access_log",
            "where occurred_at &lt; #{before}",
            "<if test='excludeIds != null and excludeIds.size > 0'>",
            "and id not in",
            "<foreach collection='excludeIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "</if>",
            "order by occurred_at asc, id asc",
            "limit #{limit}",
            "</script>"})
    List<DataIngestionAccessLogEntity> selectExpiredArchivePointers(@Param("before") LocalDateTime before,
                                                                    @Param("limit") int limit,
                                                                    @Param("excludeIds") List<Long> excludeIds);

    @Delete({"<script>",
            "delete from data_ingestion_access_log where id in",
            "<foreach collection='ids' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "</script>"})
    int deleteExpiredByIds(@Param("ids") List<Long> ids);

    @SelectProvider(type = OpenServiceMetricSqlProvider.class, method = "selectDataIngestionDashboardSummary")
    DataIngestionApiMetricView selectDashboardSummary(@Param("tenantId") String tenantId,
                                                      @Param("projectId") Long projectId,
                                                      @Param("serviceIds") List<Long> serviceIds,
                                                      @Param("requestedClusterId") Long requestedClusterId,
                                                      @Param("actualClusterId") Long actualClusterId,
                                                      @Param("subscriptionId") Long subscriptionId,
                                                      @Param("noTokenSubscription") boolean noTokenSubscription,
                                                      @Param("success") Integer success,
                                                      @Param("logFocus") String logFocus,
                                                      @Param("minDurationMs") Long minDurationMs,
                                                      @Param("startTime") LocalDateTime startTime,
                                                      @Param("endTime") LocalDateTime endTime,
                                                      @Param("hourGranularity") boolean hourGranularity);

    @SelectProvider(type = OpenServiceMetricSqlProvider.class, method = "selectDataIngestionDashboardBuckets")
    List<OpenServiceDashboardBucketSummary> selectDashboardBuckets(@Param("tenantId") String tenantId,
                                                                   @Param("projectId") Long projectId,
                                                                   @Param("serviceIds") List<Long> serviceIds,
                                                                   @Param("requestedClusterId") Long requestedClusterId,
                                                                   @Param("actualClusterId") Long actualClusterId,
                                                                   @Param("subscriptionId") Long subscriptionId,
                                                                   @Param("noTokenSubscription") boolean noTokenSubscription,
                                                                   @Param("success") Integer success,
                                                                   @Param("logFocus") String logFocus,
                                                                   @Param("minDurationMs") Long minDurationMs,
                                                                   @Param("startTime") LocalDateTime startTime,
                                                                   @Param("endTime") LocalDateTime endTime,
                                                                   @Param("hourGranularity") boolean hourGranularity);

    @SelectProvider(type = OpenServiceMetricSqlProvider.class, method = "selectDataIngestionDashboardErrorDistribution")
    List<DataServiceMetricDistributionView> selectDashboardErrorDistribution(@Param("tenantId") String tenantId,
                                                                             @Param("projectId") Long projectId,
                                                                             @Param("serviceIds") List<Long> serviceIds,
                                                                             @Param("requestedClusterId") Long requestedClusterId,
                                                                             @Param("actualClusterId") Long actualClusterId,
                                                                             @Param("subscriptionId") Long subscriptionId,
                                                                             @Param("noTokenSubscription") boolean noTokenSubscription,
                                                                             @Param("success") Integer success,
                                                                             @Param("logFocus") String logFocus,
                                                                             @Param("minDurationMs") Long minDurationMs,
                                                                             @Param("startTime") LocalDateTime startTime,
                                                                             @Param("endTime") LocalDateTime endTime,
                                                                             @Param("hourGranularity") boolean hourGranularity,
                                                                             @Param("limit") int limit);

    @SelectProvider(type = OpenServiceMetricSqlProvider.class, method = "selectDataIngestionDashboardApiStats")
    List<DataIngestionApiMetricView> selectDashboardApiStats(@Param("tenantId") String tenantId,
                                                             @Param("projectId") Long projectId,
                                                             @Param("serviceIds") List<Long> serviceIds,
                                                             @Param("requestedClusterId") Long requestedClusterId,
                                                             @Param("actualClusterId") Long actualClusterId,
                                                             @Param("subscriptionId") Long subscriptionId,
                                                             @Param("noTokenSubscription") boolean noTokenSubscription,
                                                             @Param("success") Integer success,
                                                             @Param("logFocus") String logFocus,
                                                             @Param("minDurationMs") Long minDurationMs,
                                                             @Param("startTime") LocalDateTime startTime,
                                                             @Param("endTime") LocalDateTime endTime,
                                                             @Param("hourGranularity") boolean hourGranularity,
                                                             @Param("orderMode") String orderMode,
                                                             @Param("limit") int limit);

    @SelectProvider(type = OpenServiceMetricSqlProvider.class, method = "selectDataIngestionDashboardSubscriptionRank")
    List<DataIngestionApiMetricView> selectDashboardSubscriptionRank(@Param("tenantId") String tenantId,
                                                                     @Param("projectId") Long projectId,
                                                                     @Param("serviceIds") List<Long> serviceIds,
                                                                     @Param("requestedClusterId") Long requestedClusterId,
                                                                     @Param("actualClusterId") Long actualClusterId,
                                                                     @Param("subscriptionId") Long subscriptionId,
                                                                     @Param("noTokenSubscription") boolean noTokenSubscription,
                                                                     @Param("success") Integer success,
                                                                     @Param("logFocus") String logFocus,
                                                                     @Param("minDurationMs") Long minDurationMs,
                                                                     @Param("startTime") LocalDateTime startTime,
                                                                     @Param("endTime") LocalDateTime endTime,
                                                                     @Param("hourGranularity") boolean hourGranularity,
                                                                     @Param("limit") int limit);

    @Select({"<script>",
            "select count(1)",
            "from (",
            "  select service_id",
            "  from data_ingestion_access_log",
            "  where deleted = 0",
            "    and tenant_id = #{tenantId}",
            "    and project_id = #{projectId}",
            "    <if test='requestedClusterId != null'>and requested_cluster_id = #{requestedClusterId}</if>",
            "    <if test='actualClusterId != null'>and actual_cluster_id = #{actualClusterId}</if>",
            "    and service_id is not null",
            "    and occurred_at &gt;= #{startTime}",
            "    and occurred_at &lt;= #{endTime}",
            "    <choose>",
            "      <when test='serviceIds != null and serviceIds.size() &gt; 0'>",
            "        and service_id in",
            "        <foreach collection='serviceIds' item='serviceId' open='(' separator=',' close=')'>#{serviceId}</foreach>",
            "      </when>",
            "      <otherwise>and 1 = 0</otherwise>",
            "    </choose>",
            "    <if test='subscriptionId != null'>and subscription_id = #{subscriptionId}</if>",
            "    <if test='noTokenSubscription'>and subscription_id is null</if>",
            "    <if test='success != null'>and success = #{success}</if>",
            "    <if test='logFocus == \"ERROR\"'>and success &lt;&gt; 1</if>",
            "    <if test='logFocus == \"SLOW\"'>and duration_ms &gt;= #{minDurationMs}</if>",
            "    <if test='logFocus == \"ERROR_OR_SLOW\"'>and (success &lt;&gt; 1 or duration_ms &gt;= #{minDurationMs})</if>",
            "  group by service_id",
            ") grouped",
            "</script>"})
    long countApiStats(@Param("tenantId") String tenantId,
                       @Param("projectId") Long projectId,
                       @Param("serviceIds") List<Long> serviceIds,
                       @Param("requestedClusterId") Long requestedClusterId,
                       @Param("actualClusterId") Long actualClusterId,
                       @Param("subscriptionId") Long subscriptionId,
                       @Param("noTokenSubscription") boolean noTokenSubscription,
                       @Param("success") Integer success,
                       @Param("logFocus") String logFocus,
                       @Param("minDurationMs") Long minDurationMs,
                       @Param("startTime") LocalDateTime startTime,
                       @Param("endTime") LocalDateTime endTime);

    @Select({"<script>",
            "with filtered as (",
            "  select",
            "    id, service_id, occurred_at, coalesce(duration_ms, 0) as duration_ms, success, received_count, success_count, failed_count",
            "  from data_ingestion_access_log",
            "  where deleted = 0",
            "    and tenant_id = #{tenantId}",
            "    and project_id = #{projectId}",
            "    <if test='requestedClusterId != null'>and requested_cluster_id = #{requestedClusterId}</if>",
            "    <if test='actualClusterId != null'>and actual_cluster_id = #{actualClusterId}</if>",
            "    and service_id is not null",
            "    and occurred_at &gt;= #{startTime}",
            "    and occurred_at &lt;= #{endTime}",
            "    <choose>",
            "      <when test='serviceIds != null and serviceIds.size() &gt; 0'>",
            "        and service_id in",
            "        <foreach collection='serviceIds' item='serviceId' open='(' separator=',' close=')'>#{serviceId}</foreach>",
            "      </when>",
            "      <otherwise>and 1 = 0</otherwise>",
            "    </choose>",
            "    <if test='subscriptionId != null'>and subscription_id = #{subscriptionId}</if>",
            "    <if test='noTokenSubscription'>and subscription_id is null</if>",
            "    <if test='success != null'>and success = #{success}</if>",
            "    <if test='logFocus == \"ERROR\"'>and success &lt;&gt; 1</if>",
            "    <if test='logFocus == \"SLOW\"'>and duration_ms &gt;= #{minDurationMs}</if>",
            "    <if test='logFocus == \"ERROR_OR_SLOW\"'>and (success &lt;&gt; 1 or duration_ms &gt;= #{minDurationMs})</if>",
            "),",
            "grouped as (",
            "  select",
            "    service_id,",
            "    count(1) as access_count,",
            "    coalesce(sum(case when success = 1 then 1 else 0 end), 0) as success_count,",
            "    coalesce(sum(case when success = 1 then 0 else 1 end), 0) as failure_count,",
            "    coalesce(sum(received_count), 0) as received_count,",
            "    coalesce(sum(success_count), 0) as written_count,",
            "    coalesce(sum(failed_count), 0) as failed_count,",
            "    coalesce(min(duration_ms), 0) as min_response_time_ms,",
            "    coalesce(max(duration_ms), 0) as max_response_time_ms,",
            "    coalesce(round(avg(duration_ms)), 0) as avg_response_time_ms,",
            "    max(occurred_at) as last_access_at",
            "  from filtered",
            "  group by service_id",
            "),",
            "ranked as (",
            "  select",
            "    service_id,",
            "    duration_ms,",
            "    row_number() over (partition by service_id order by duration_ms asc, id asc) as rn,",
            "    count(1) over (partition by service_id) as cnt",
            "  from filtered",
            "),",
            "percentiles as (",
            "  select",
            "    service_id,",
            "    coalesce(max(case when rn = ceiling(cnt * 0.95) then duration_ms end), 0) as p95_response_time_ms,",
            "    coalesce(max(case when rn = ceiling(cnt * 0.99) then duration_ms end), 0) as p99_response_time_ms",
            "  from ranked",
            "  group by service_id",
            ")",
            "select",
            "  g.service_id as service_id,",
            "  g.access_count as access_count,",
            "  g.success_count as success_count,",
            "  g.failure_count as failure_count,",
            "  g.received_count as received_count,",
            "  g.written_count as written_count,",
            "  g.failed_count as failed_count,",
            "  g.min_response_time_ms as min_response_time_ms,",
            "  g.max_response_time_ms as max_response_time_ms,",
            "  g.avg_response_time_ms as avg_response_time_ms,",
            "  coalesce(p.p95_response_time_ms, 0) as p95_response_time_ms,",
            "  coalesce(p.p99_response_time_ms, 0) as p99_response_time_ms,",
            "  g.last_access_at as last_access_at",
            "from grouped g",
            "left join percentiles p on p.service_id = g.service_id",
            "order by g.access_count desc, g.last_access_at desc",
            "limit #{limit} offset #{offset}",
            "</script>"})
    List<DataIngestionApiMetricView> selectApiStatsPage(@Param("tenantId") String tenantId,
                                                        @Param("projectId") Long projectId,
                                                        @Param("serviceIds") List<Long> serviceIds,
                                                        @Param("requestedClusterId") Long requestedClusterId,
                                                        @Param("actualClusterId") Long actualClusterId,
                                                        @Param("subscriptionId") Long subscriptionId,
                                                        @Param("noTokenSubscription") boolean noTokenSubscription,
                                                        @Param("success") Integer success,
                                                        @Param("logFocus") String logFocus,
                                                        @Param("minDurationMs") Long minDurationMs,
                                                        @Param("startTime") LocalDateTime startTime,
                                                        @Param("endTime") LocalDateTime endTime,
                                                        @Param("limit") int limit,
                                                        @Param("offset") int offset);
}
