create table if not exists protocol_conversion_service (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    service_code varchar(128) not null,
    service_name varchar(255) not null,
    status varchar(64) not null,
    endpoint_path varchar(1000),
    webservice_endpoint_path varchar(1000),
    service_key varchar(128),
    token_required int default 1,
    default_subscription_name varchar(255),
    source_protocol varchar(32) not null,
    source_method varchar(16),
    source_data_node_path varchar(500),
    webservice_config_json json,
    conversion_mode varchar(32) not null,
    field_mappings_json json,
    raw_transformers_json json,
    fixed_fields_json json,
    body_bridge_options_json json,
    request_passthrough_json json,
    target_datasource_id bigint,
    target_datasource_name_snapshot varchar(255),
    target_path varchar(1000),
    target_protocol varchar(32) not null,
    target_method varchar(16),
    target_headers_json json,
    target_query_json json,
    target_webservice_config_json json,
    target_body_template mediumtext,
    target_data_node_path varchar(500),
    payload_mode varchar(32),
    batch_size int default 1,
    response_status_json json,
    unique key uk_protocol_conversion_project_code (tenant_id, project_id, service_code),
    key idx_protocol_conversion_project_status (project_id, status),
    key idx_protocol_conversion_code_key (service_code, service_key)
);

create table if not exists protocol_conversion_subscription (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    subscription_name varchar(255) not null,
    token_hash varchar(128) not null,
    token_masked varchar(64),
    enabled int default 1,
    created_by bigint,
    last_used_at datetime,
    rotated_at datetime,
    rotated_by bigint,
    key idx_protocol_conversion_sub_service_enabled (service_id, enabled),
    key idx_protocol_conversion_sub_token (token_hash)
);

create table if not exists protocol_conversion_access_log (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint,
    service_code_snapshot varchar(255),
    service_name_snapshot varchar(255),
    service_status_snapshot varchar(64),
    subscription_id bigint,
    subscription_name_snapshot varchar(255),
    request_id varchar(128),
    request_method varchar(16),
    source_protocol_snapshot varchar(32),
    target_protocol_snapshot varchar(32),
    occurred_at datetime,
    duration_ms bigint,
    success int default 0,
    http_status int,
    target_http_status int,
    error_code varchar(128),
    error_message varchar(1000),
    system_log mediumtext,
    client_ip varchar(128),
    user_agent varchar(500),
    received_count bigint default 0,
    success_count bigint default 0,
    failed_count bigint default 0,
    key idx_protocol_conversion_access_project_time (tenant_id, project_id, occurred_at),
    key idx_protocol_conversion_access_service_time (service_id, occurred_at),
    key idx_protocol_conversion_access_subscription_time (subscription_id, occurred_at),
    key idx_protocol_conversion_access_success (project_id, success, occurred_at)
);

create table if not exists protocol_conversion_access_counter (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null default 0,
    subscription_id bigint not null default 0,
    bucket_start datetime not null,
    success int not null default 0,
    access_count bigint default 0,
    received_count bigint default 0,
    success_count bigint default 0,
    failed_count bigint default 0,
    unique key uk_protocol_conversion_access_counter (tenant_id, project_id, service_id, subscription_id, bucket_start, success),
    key idx_protocol_conversion_counter_project_bucket (tenant_id, project_id, bucket_start),
    key idx_protocol_conversion_counter_service_bucket (service_id, bucket_start)
);
