create table if not exists sys_user (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    username varchar(128) not null,
    password_hash varchar(255) not null,
    display_name varchar(255),
    mobile_phone varchar(32),
    enabled int default 1,
    auth_source varchar(32) default 'LOCAL',
    unique key uk_sys_user_username (username)
);

create table if not exists studio_external_user_binding (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    provider_code varchar(64) not null,
    external_user_id varchar(128) not null,
    external_account varchar(255),
    studio_user_id bigint not null,
    last_seen_at datetime,
    unique key uk_studio_external_user_binding_external (provider_code, external_user_id),
    unique key uk_studio_external_user_binding_provider_user (provider_code, studio_user_id),
    key idx_studio_external_user_binding_user (studio_user_id)
);

create table if not exists sys_role (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    code varchar(128) not null,
    name varchar(255) not null,
    description varchar(500),
    unique key uk_sys_role_code (code)
);

create table if not exists sys_permission (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    code varchar(128) not null,
    name varchar(255) not null,
    http_method varchar(32),
    path_pattern varchar(255),
    unique key uk_sys_permission_code (code)
);

create table if not exists sys_user_role (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    user_id bigint not null,
    role_id bigint not null
);

create table if not exists sys_role_permission (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    role_id bigint not null,
    permission_id bigint not null
);

create table if not exists studio_tenant (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    tenant_code varchar(64) not null,
    tenant_name varchar(255) not null,
    description varchar(1000),
    enabled int default 1,
    unique key uk_studio_tenant_code (tenant_code)
);

create table if not exists studio_project (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    project_code varchar(128) not null,
    project_name varchar(255) not null,
    description varchar(1000),
    enabled int default 1,
    default_project int default 0,
    unique key uk_studio_project_code (tenant_id, project_code),
    unique key uk_studio_project_name (tenant_id, project_name)
);

create table if not exists studio_runtime_cluster (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    code varchar(64) not null,
    name varchar(255) not null,
    enabled int default 1,
    status varchar(32) default 'UNKNOWN',
    version varchar(128),
    last_heartbeat_at datetime,
    instances_json json,
    unique key uk_runtime_cluster_tenant_code (tenant_id, code),
    key idx_runtime_cluster_tenant_enabled (tenant_id, enabled)
);

create table if not exists studio_runtime_endpoint (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    runtime_cluster_id bigint not null,
    mode varchar(32) not null,
    endpoint_ciphertext text,
    headers_ciphertext text,
    token_ciphertext text,
    connect_timeout_millis int default 3000,
    read_timeout_millis int default 5000,
    enabled int default 1,
    last_tested_at datetime,
    last_test_status varchar(32),
    last_test_message varchar(1000),
    key idx_runtime_endpoint_cluster (tenant_id, runtime_cluster_id, enabled)
);

create table if not exists studio_runtime_idempotency (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint not null,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    runtime_cluster_id bigint,
    resource_type varchar(64) not null,
    resource_id bigint not null,
    key_hash char(64) not null,
    request_fingerprint char(64) not null,
    status varchar(16) not null,
    owner_token_hash char(64) not null,
    owner_instance_id varchar(128) not null,
    owner_boot_id varchar(128) not null,
    response_status int,
    response_content_type varchar(512),
    response_body_ciphertext longtext,
    completed_at datetime,
    version int default 0,
    unique key uk_runtime_idem_scope_key (tenant_id, project_id, resource_type, resource_id, key_hash),
    key idx_runtime_idem_status_updated (status, updated_at)
);

create table if not exists studio_project_runtime_cluster (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint not null,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    runtime_cluster_id bigint not null,
    enabled int default 1,
    preferred int default 0,
    allow_manual_override int default 0,
    unique key uk_project_runtime_cluster (tenant_id, project_id, runtime_cluster_id),
    key idx_project_runtime_cluster_options (tenant_id, project_id, enabled, preferred)
);

create table if not exists studio_tenant_member (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    user_id bigint not null,
    role_code varchar(128) not null,
    status varchar(64) not null,
    unique key uk_studio_tenant_member_user (tenant_id, user_id)
);

create table if not exists studio_project_member (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    project_id bigint not null,
    user_id bigint not null,
    role_code varchar(128) not null,
    status varchar(64) not null,
    unique key uk_studio_project_member_user (project_id, user_id)
);

create table if not exists studio_project_member_request (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    project_id bigint not null,
    user_id bigint not null,
    request_type varchar(64) not null,
    status varchar(64) not null,
    inviter_user_id bigint,
    reviewer_user_id bigint,
    reason varchar(1000),
    review_comment varchar(1000),
    key idx_studio_project_member_request_lookup (project_id, user_id, status)
);

create table if not exists studio_project_worker_binding (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    project_id bigint not null,
    worker_group_code varchar(255),
    worker_code varchar(255) not null,
    enabled int default 1,
    unique key uk_studio_project_worker_binding (project_id, worker_code),
    key idx_studio_project_worker_group (project_id, worker_group_code)
);

create table if not exists studio_resource_share (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    source_project_id bigint not null,
    target_project_id bigint not null,
    resource_type varchar(128) not null,
    resource_id bigint not null,
    shared_by_user_id bigint,
    enabled int default 1,
    unique key uk_studio_resource_share_target (resource_type, resource_id, target_project_id),
    key idx_studio_resource_share_project (target_project_id)
);

create table if not exists datasource_type_capability (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    type_code varchar(128) not null,
    type_name varchar(255) not null,
    enabled int default 1,
    readable int default 0,
    writable int default 0,
    executable int default 0,
    sql_executable int default 0,
    source_category varchar(32) not null default 'DATABASE',
    source_plugin varchar(128),
    reader_plugins_json json,
    writer_plugins_json json,
    runtime_capabilities_json json,
    sort_order int default 0,
    description varchar(1000),
    unique key uk_datasource_type_capability_code (tenant_id, type_code)
);

create table if not exists field_mapping_rule (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    mapping_name varchar(255) not null,
    mapping_type varchar(255) not null,
    mapping_code varchar(255) not null,
    enabled int default 1,
    description varchar(1000),
    created_by bigint,
    unique key uk_field_mapping_rule_code (mapping_code),
    key idx_field_mapping_rule_type_enabled (mapping_type, enabled),
    key idx_field_mapping_rule_created_at (created_at)
);

create table if not exists field_mapping_rule_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    rule_id bigint not null,
    param_name varchar(255) not null,
    param_order int not null,
    component_type varchar(64) not null,
    param_value_json text,
    description varchar(1000),
    key idx_field_mapping_rule_param_rule_order (rule_id, param_order),
    key idx_field_mapping_rule_param_rule_name (rule_id, param_name)
);

create table if not exists quality_rule (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    rule_name varchar(255) not null,
    rule_code varchar(255) not null,
    scope_type varchar(32) not null,
    rule_dimension varchar(64) not null,
    description varchar(2000),
    supported_datasource_types_json json,
    granularity varchar(32) not null,
    logic_sql text,
    enabled int default 1,
    unique key uk_quality_rule_scope_code (tenant_id, project_id, scope_type, rule_code),
    key idx_quality_rule_scope_enabled (tenant_id, project_id, scope_type, enabled),
    key idx_quality_rule_dimension_enabled (rule_dimension, enabled)
);

create table if not exists quality_rule_input_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    rule_id bigint not null,
    param_order int not null,
    param_name varchar(255) not null,
    param_type varchar(32) not null,
    param_meaning varchar(1000),
    key idx_quality_rule_input_param_rule_order (rule_id, param_order),
    key idx_quality_rule_input_param_rule_name (rule_id, param_name)
);

create table if not exists quality_rule_output_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    rule_id bigint not null,
    output_order int not null,
    result_field varchar(255) not null,
    output_type varchar(32) not null,
    output_description varchar(1000),
    key idx_quality_rule_output_param_rule_order (rule_id, output_order),
    key idx_quality_rule_output_param_rule_field (rule_id, result_field)
);

create table if not exists user_registration_request (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    status varchar(64) not null,
    username varchar(128) not null,
    password_hash varchar(255) not null,
    display_name varchar(255),
    reason varchar(1000),
    review_comment varchar(1000),
    reviewer_user_id bigint,
    approved_user_id bigint,
    reviewed_at datetime,
    key idx_user_registration_request_status_created (status, created_at),
    unique key uk_user_registration_request_username_status (username, status)
);

create table if not exists studio_notification (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    recipient_user_id bigint not null,
    tenant_id varchar(64),
    project_id bigint,
    category varchar(128),
    title varchar(255),
    content varchar(2000),
    target_type varchar(128),
    target_id bigint,
    target_path varchar(1000),
    target_tenant_id varchar(64),
    target_project_id bigint,
    dedupe_key varchar(255),
    read_at datetime,
    archived_at datetime,
    payload_json json,
    key idx_studio_notification_recipient_created (recipient_user_id, created_at),
    key idx_studio_notification_recipient_unread (recipient_user_id, read_at, archived_at),
    unique key uk_studio_notification_recipient_dedupe (recipient_user_id, dedupe_key)
);

create table if not exists studio_follow_subscription (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    user_id bigint not null,
    target_type varchar(128) not null,
    target_id bigint not null,
    enabled int default 1,
    unique key uk_studio_follow_subscription_target (tenant_id, project_id, user_id, target_type, target_id),
    key idx_studio_follow_subscription_lookup (target_type, target_id, enabled)
);

create table if not exists meta_schema (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    schema_code varchar(255),
    schema_name varchar(255),
    object_type varchar(128),
    type_code varchar(255),
    current_version_id bigint,
    status varchar(64),
    description varchar(1000)
);

create table if not exists meta_schema_version (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    schema_id bigint,
    version_number int,
    status varchar(64),
    description varchar(1000)
);

create table if not exists meta_field_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    schema_version_id bigint,
    field_key varchar(255),
    field_name varchar(255),
    description varchar(1000),
    scope varchar(64),
    value_type varchar(64),
    component_type varchar(64),
    file_policy_code varchar(64),
    required_flag int default 0,
    sensitive_flag int default 0,
    sort_order int default 0,
    validation_rule varchar(1000),
    placeholder varchar(255),
    default_value varchar(1000),
    searchable_flag int default 0,
    sortable_flag int default 0,
    query_operators json,
    query_default_operator varchar(64),
    options json
);

create table if not exists datasource_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    name varchar(255),
    type_code varchar(128),
    schema_version_id bigint,
    enabled int default 1,
    executable int default 0,
    connection_fingerprint varchar(128),
    connection_status varchar(32) default 'UNKNOWN',
    last_connection_test_at datetime,
    last_connection_test_message varchar(1000),
    last_connection_test_duration_ms bigint,
    manual_connection_test_timeout_seconds int,
    scheduled_connection_test_timeout_seconds int,
    technical_metadata json,
    business_metadata json,
    unique key uk_datasource_definition_project_name (project_id, name),
    key idx_datasource_definition_project (project_id),
    key idx_datasource_definition_connection (tenant_id, connection_fingerprint)
);

create table if not exists unstructured_source_acl (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint not null,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    datasource_id bigint not null,
    principal_type varchar(32) not null,
    user_id bigint,
    permission varchar(32) not null,
    effect varchar(32) not null,
    created_by bigint,
    unique key uk_unstructured_source_acl (tenant_id, datasource_id, principal_type, user_id, permission),
    key idx_unstructured_source_acl_source (tenant_id, project_id, datasource_id)
);

create table if not exists unstructured_path_acl (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint not null,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    datasource_id bigint not null,
    path varchar(2000) not null,
    directory int default 1,
    principal_type varchar(32) not null,
    user_id bigint,
    permission varchar(32) not null,
    effect varchar(32) not null,
    created_by bigint,
    unique key uk_unstructured_path_acl (tenant_id, datasource_id, path(255), principal_type, user_id, permission),
    key idx_unstructured_path_acl_source (tenant_id, project_id, datasource_id, path(255))
);

create table if not exists unstructured_op_audit (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint not null,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    datasource_id bigint not null,
    runtime_cluster_id bigint not null,
    user_id bigint,
    username varchar(255),
    operation varchar(32) not null,
    source_path varchar(2000),
    target_path varchar(2000),
    `recursive` int default 0,
    status varchar(32) not null,
    message text,
    key idx_unstructured_op_audit_source (tenant_id, project_id, datasource_id, created_at)
);

create table if not exists datasource_cluster_binding (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    datasource_id bigint not null,
    runtime_cluster_id bigint not null,
    enabled int default 1,
    unique key uk_datasource_cluster_binding (tenant_id, datasource_id, runtime_cluster_id),
    key idx_datasource_cluster_options (tenant_id, runtime_cluster_id, enabled, datasource_id)
);

create table if not exists studio_runtime_validation (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint not null,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    resource_type varchar(64) not null,
    resource_id bigint not null,
    runtime_cluster_id bigint,
    valid int default 1,
    issue_code varchar(128),
    issue_message varchar(1000),
    details_json json,
    validated_at datetime,
    unique key uk_runtime_validation_resource (tenant_id, project_id, resource_type, resource_id),
    key idx_runtime_validation_invalid (tenant_id, project_id, valid, resource_type)
);

create table if not exists datasource_connection_health (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    runtime_cluster_id bigint,
    connection_fingerprint varchar(128) not null,
    legacy_connection_fingerprint varchar(128) generated always as
        (case when runtime_cluster_id is null then connection_fingerprint else null end) stored,
    connection_status varchar(32) default 'UNKNOWN',
    last_connection_test_at datetime,
    last_connection_test_message varchar(1000),
    last_connection_test_duration_ms bigint,
    probe_state varchar(32) default 'IDLE',
    probe_owner varchar(128),
    probe_run_id varchar(64),
    probe_started_at datetime,
    probe_lease_until datetime,
    failure_count int default 0,
    next_probe_at datetime,
    unique key uk_ds_conn_health_fp (tenant_id, runtime_cluster_id, connection_fingerprint),
    unique key uk_ds_conn_health_legacy_fp (tenant_id, legacy_connection_fingerprint),
    key idx_ds_conn_health_next (next_probe_at),
    key idx_ds_conn_health_probe (probe_state, probe_lease_until)
);

create table if not exists datasource_connection_test_record (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    runtime_cluster_id bigint,
    connection_fingerprint varchar(128) not null,
    datasource_id bigint,
    datasource_name varchar(255),
    type_code varchar(128),
    probe_run_id varchar(64) not null,
    probe_mode varchar(32),
    connection_status varchar(32) default 'UNKNOWN',
    started_at datetime,
    ended_at datetime,
    duration_ms bigint,
    timeout_seconds int,
    message varchar(1000),
    unique key uk_ds_conn_record_run (tenant_id, probe_run_id),
    key idx_ds_conn_record_lookup (tenant_id, connection_fingerprint, ended_at),
    key idx_ds_conn_record_cluster_lookup (tenant_id, runtime_cluster_id, connection_fingerprint, ended_at),
    key idx_ds_conn_record_cleanup (ended_at)
);

create table if not exists data_model (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    datasource_id bigint,
    name varchar(255),
    model_kind varchar(64),
    physical_locator varchar(1000),
    schema_version_id bigint,
    technical_metadata json,
    business_metadata json,
    unique key uk_data_model_project_datasource_name (project_id, datasource_id, name),
    key idx_data_model_project (project_id),
    key idx_data_model_tenant_project_created (tenant_id, project_id, created_at),
    key idx_data_model_tenant_datasource_created (tenant_id, datasource_id, created_at)
);

create table if not exists model_sync_task (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    runtime_cluster_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    datasource_id bigint not null,
    datasource_type varchar(128),
    datasource_name_snapshot varchar(255),
    batch_no int not null,
    name varchar(255) not null,
    source varchar(64),
    status varchar(64),
    total_count int default 0,
    success_count int default 0,
    failed_count int default 0,
    stopped_count int default 0,
    progress_percent int default 0,
    stop_requested int default 0,
    created_by bigint,
    started_at datetime,
    finished_at datetime,
    duration_ms bigint,
    last_error varchar(2000),
    unique key uk_model_sync_task_project_datasource_batch (project_id, datasource_id, batch_no),
    key idx_model_sync_task_project_created (project_id, created_at),
    key idx_model_sync_task_project_status (project_id, status),
    key idx_model_sync_task_project_cluster_status (project_id, runtime_cluster_id, status)
);

create table if not exists model_sync_task_item (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    task_id bigint not null,
    seq_no int not null,
    physical_locator varchar(1000),
    model_name_snapshot varchar(255),
    status varchar(64),
    message varchar(2000),
    started_at datetime,
    finished_at datetime,
    duration_ms bigint,
    key idx_model_sync_task_item_task_seq (task_id, seq_no),
    key idx_model_sync_task_item_task_status (task_id, status)
);

create table if not exists data_model_attr_index (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    model_id bigint,
    datasource_id bigint,
    meta_schema_version_id bigint,
    meta_schema_code varchar(255),
    scope varchar(64),
    meta_model_code varchar(128),
    item_key varchar(255),
    field_key varchar(255),
    value_type varchar(64),
    keyword_value varchar(1000),
    text_value text,
    number_value decimal(38, 10),
    bool_value int,
    raw_value text,
    key idx_model_attr_index_project (project_id),
    key idx_model_attr_index_model (model_id),
    key idx_model_attr_index_tenant_model_item (tenant_id, model_id, item_key),
    key idx_model_attr_index_datasource (datasource_id),
    key idx_model_attr_index_lookup (meta_schema_code(128), scope, field_key(128), keyword_value(128)),
    key idx_model_attr_index_number (meta_schema_code, scope, field_key, number_value),
    key idx_model_attr_index_tenant_lookup (tenant_id, meta_schema_code(128), scope, field_key(128), keyword_value(128)),
    key idx_model_attr_index_tenant_number (tenant_id, meta_schema_code(128), scope, field_key(128), number_value)
);

create table if not exists workflow_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    runtime_cluster_id bigint,
    code varchar(255),
    name varchar(255),
    current_version_id bigint,
    published int default 0,
    unique key uk_workflow_definition_project_code (project_id, code),
    unique key uk_workflow_definition_project_name (project_id, name),
    key idx_workflow_definition_project (project_id)
);

create table if not exists workflow_definition_version (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    definition_id bigint,
    runtime_cluster_id bigint,
    version_number int,
    published int default 0,
    graph_json json,
    schedule_json json,
    key idx_workflow_definition_version_project (project_id)
);

create table if not exists workflow_node (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    workflow_version_id bigint,
    node_code varchar(255),
    node_name varchar(255),
    node_type varchar(128),
    config_json json,
    field_mappings_json json,
    key idx_workflow_node_project (project_id)
);

create table if not exists workflow_edge (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    workflow_version_id bigint,
    from_node_code varchar(255),
    to_node_code varchar(255),
    condition_type varchar(64),
    key idx_workflow_edge_project (project_id)
);

create table if not exists workflow_schedule (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    workflow_definition_id bigint,
    cron_expression varchar(255),
    enabled int default 0,
    timezone varchar(64),
    last_triggered_at datetime,
    key idx_workflow_schedule_project (project_id)
);

create table if not exists collection_task_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    runtime_cluster_id bigint,
    name varchar(255),
    task_type varchar(64),
    status varchar(64),
    execution_mode varchar(32) not null default 'BATCH',
    source_count int default 1,
    target_datasource_name_snapshot varchar(255),
    target_datasource_type_code_snapshot varchar(128),
    target_model_name_snapshot varchar(255),
    target_model_physical_locator_snapshot varchar(512),
    source_bindings_json json,
    target_binding_json json,
    field_mappings_json json,
    execution_options_json json,
    streaming_options_json json,
    unique key uk_collection_task_definition_project_name (project_id, name),
    key idx_collection_task_definition_project (project_id)
);

create table if not exists collection_task_metric_binding (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    collection_task_id bigint not null,
    task_name_snapshot varchar(255),
    task_type varchar(64),
    task_status varchar(64),
    source_count int default 1,
    binding_role varchar(32) not null,
    source_alias varchar(255),
    datasource_id bigint,
    datasource_name varchar(255),
    datasource_type_code varchar(128),
    model_id bigint,
    model_name varchar(255),
    model_physical_locator varchar(512),
    key idx_collection_metric_project_task (project_id, collection_task_id),
    key idx_collection_metric_role_ds (binding_role, datasource_id),
    key idx_collection_metric_role_model (binding_role, model_id)
);

create table if not exists collection_task_schedule (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    collection_task_id bigint,
    cron_expression varchar(255),
    enabled int default 0,
    timezone varchar(64),
    last_triggered_at datetime,
    key idx_collection_task_schedule_project (project_id)
);

create table if not exists so_pf_managed_file (
    id bigint primary key,
    tenant_id varchar(64) not null default 'default',
    project_id bigint not null,
    deleted int not null default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    original_file_name varchar(255) not null,
    policy_code varchar(64) not null,
    content_type varchar(255),
    plaintext_size bigint,
    ciphertext_size bigint,
    sha256 varchar(64),
    object_bucket varchar(255),
    object_key varchar(1000),
    encryption_algorithm varchar(64),
    encryption_version int,
    encryption_iv varchar(128),
    status varchar(32) not null,
    expires_at datetime,
    bound_at datetime,
    last_referenced_at datetime,
    uploaded_by bigint,
    error_message varchar(1000),
    delete_retry_count int not null default 0,
    next_delete_attempt_at datetime,
    deleted_at datetime,
    key idx_mfile_project_status (tenant_id, project_id, status, created_at),
    key idx_mfile_gc (status, expires_at, next_delete_attempt_at),
    key idx_mfile_sha (tenant_id, project_id, sha256)
);

create table if not exists so_pf_managed_file_ref (
    id bigint primary key,
    tenant_id varchar(64) not null default 'default',
    project_id bigint not null,
    deleted int not null default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    file_id bigint not null,
    owner_type varchar(64) not null,
    owner_id bigint not null,
    field_key varchar(255) not null,
    ordinal int not null default 0,
    unique key uk_mfile_ref_owner (tenant_id, project_id, owner_type, owner_id, field_key, ordinal),
    key idx_mfile_ref_file (file_id),
    key idx_mfile_ref_owner (tenant_id, project_id, owner_type, owner_id)
);

create table if not exists so_pf_managed_file_lease (
    id bigint primary key,
    tenant_id varchar(64) not null default 'default',
    project_id bigint not null,
    deleted int not null default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    file_id bigint not null,
    lease_token varchar(64) not null,
    consumer_type varchar(64),
    consumer_id varchar(255),
    worker_instance_id varchar(255),
    heartbeat_at datetime,
    expires_at datetime not null,
    released_at datetime,
    unique key uk_mfile_lease_token (lease_token),
    key idx_mfile_lease_active (file_id, released_at, expires_at)
);

create table if not exists so_pf_managed_file_audit (
    id bigint primary key,
    tenant_id varchar(64) not null default 'default',
    project_id bigint not null,
    deleted int not null default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    file_id bigint,
    action varchar(64) not null,
    outcome varchar(32) not null,
    actor_user_id bigint,
    actor_name varchar(255),
    owner_type varchar(64),
    owner_id bigint,
    field_key varchar(255),
    detail varchar(1000),
    key idx_mfile_audit_file (tenant_id, project_id, file_id, created_at),
    key idx_mfile_audit_time (created_at)
);

create table if not exists stream_task_deploy (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    collection_task_id bigint not null,
    runtime_cluster_id bigint,
    generation bigint not null default 0,
    desired_state varchar(32) not null default 'STOPPED',
    observed_state varchar(32) not null default 'STOPPED',
    current_run_id bigint,
    current_attempt_id bigint,
    consecutive_failure_count int not null default 0,
    next_retry_at datetime,
    last_checkpoint_json json,
    last_checkpoint_at datetime,
    last_error_code varchar(128),
    last_error_summary varchar(1000),
    version int not null default 0,
    unique key uk_stream_deploy_task (tenant_id, project_id, collection_task_id),
    key idx_stream_deploy_state (tenant_id, runtime_cluster_id, desired_state, observed_state, next_retry_at)
);

create table if not exists stream_task_run (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    collection_task_id bigint not null,
    generation bigint not null,
    runtime_cluster_id bigint,
    status varchar(32) not null,
    delivery_semantics varchar(32) not null default 'AT_LEAST_ONCE',
    group_id varchar(255) not null,
    started_by bigint,
    started_at datetime,
    stop_requested_at datetime,
    stopped_by bigint,
    stopped_at datetime,
    stop_reason varchar(1000),
    final_checkpoint_json json,
    unique key uk_stream_run_task_gen (tenant_id, project_id, collection_task_id, generation),
    key idx_stream_run_task_time (tenant_id, project_id, collection_task_id, started_at)
);

create table if not exists stream_task_attempt (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    run_id bigint not null,
    collection_task_id bigint not null,
    generation bigint not null,
    attempt_no int not null,
    dispatch_task_id bigint,
    run_record_id bigint,
    runtime_cluster_id bigint,
    worker_instance_id varchar(255),
    worker_boot_id varchar(128),
    status varchar(32) not null,
    started_at datetime,
    ended_at datetime,
    heartbeat_at datetime,
    retry_after datetime,
    checkpoint_json json,
    error_code varchar(128),
    error_summary varchar(1000),
    committed_batch_count bigint not null default 0,
    unique key uk_stream_attempt_run_no (tenant_id, project_id, run_id, attempt_no),
    key idx_stream_attempt_task_status (tenant_id, project_id, collection_task_id, status, updated_at)
);

create table if not exists stream_metric_bucket (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    collection_task_id bigint not null,
    run_id bigint not null,
    attempt_id bigint not null,
    bucket_start datetime not null,
    records_read bigint not null default 0,
    write_succeed_records bigint not null default 0,
    write_failed_records bigint not null default 0,
    dirty_records bigint not null default 0,
    bytes_read bigint not null default 0,
    batch_count bigint not null default 0,
    retry_count bigint not null default 0,
    current_lag bigint not null default 0,
    max_lag bigint not null default 0,
    last_message_at datetime,
    last_checkpoint_at datetime,
    rebalance_count bigint not null default 0,
    unique key uk_stream_metric_attempt_min (tenant_id, project_id, attempt_id, bucket_start),
    key idx_stream_metric_task_time (tenant_id, project_id, collection_task_id, bucket_start)
);

create table if not exists stream_task_event (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    collection_task_id bigint not null,
    deployment_id bigint,
    run_id bigint,
    attempt_id bigint,
    generation bigint,
    event_type varchar(64) not null,
    from_state varchar(32),
    to_state varchar(32),
    message varchar(1000),
    details_json json,
    actor_id bigint,
    occurred_at datetime not null,
    key idx_stream_event_task_time (tenant_id, project_id, collection_task_id, occurred_at),
    key idx_stream_event_run_attempt (run_id, attempt_id, occurred_at)
);

create table if not exists run_log_chunk (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    collection_task_id bigint,
    run_record_id bigint,
    stream_attempt_id bigint,
    sequence_no int not null,
    status varchar(32) not null,
    local_path varchar(1000),
    storage_type varchar(32),
    object_bucket varchar(255),
    object_key varchar(1000),
    size_bytes bigint not null default 0,
    checksum_sha256 varchar(64),
    chunk_started_at datetime,
    chunk_ended_at datetime,
    uploaded_at datetime,
    unique key uk_run_log_chunk_attempt_seq (tenant_id, project_id, stream_attempt_id, sequence_no),
    key idx_run_log_chunk_record_seq (run_record_id, sequence_no),
    key idx_run_log_chunk_task_time (collection_task_id, chunk_started_at)
);

create table if not exists quality_task_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    runtime_cluster_id bigint,
    task_name varchar(255) not null,
    task_code varchar(255) not null,
    status varchar(64),
    rule_id bigint not null,
    rule_name_snapshot varchar(255),
    rule_dimension varchar(64),
    granularity varchar(32),
    datasource_id bigint,
    datasource_name_snapshot varchar(255),
    datasource_type_code varchar(128),
    model_id bigint,
    model_name_snapshot varchar(255),
    model_physical_locator varchar(500),
    column_name varchar(255),
    where_clause text,
    resolved_sql_preview text,
    parameter_bindings_json json,
    rule_snapshot_json json,
    unique key uk_quality_task_definition_project_code (project_id, task_code),
    unique key uk_quality_task_definition_project_name (project_id, task_name),
    key idx_quality_task_definition_project_status (project_id, status),
    key idx_quality_task_definition_rule_dimension (project_id, rule_dimension)
);

create table if not exists quality_task_schedule (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    quality_task_id bigint,
    cron_expression varchar(255),
    enabled int default 0,
    timezone varchar(64),
    last_triggered_at datetime,
    key idx_quality_task_schedule_project (project_id),
    key idx_quality_task_schedule_task (quality_task_id)
);

create table if not exists quality_task_alert (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    quality_task_id bigint not null,
    output_order int not null,
    result_field varchar(255) not null,
    output_type varchar(32) not null,
    enabled int default 0,
    operator varchar(32),
    expected_value varchar(255),
    min_value varchar(255),
    max_value varchar(255),
    key idx_quality_task_alert_task (quality_task_id),
    key idx_quality_task_alert_task_order (quality_task_id, output_order)
);

create table if not exists quality_issue (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    issue_code varchar(64),
    signature varchar(1024) not null,
    issue_type varchar(64),
    quality_task_id bigint,
    quality_task_name_snapshot varchar(255),
    rule_id bigint,
    rule_name_snapshot varchar(255),
    rule_dimension varchar(64),
    datasource_id bigint,
    datasource_name_snapshot varchar(255),
    datasource_type_code varchar(128),
    model_id bigint,
    model_name_snapshot varchar(255),
    model_physical_locator varchar(500),
    column_name varchar(255),
    output_field varchar(255),
    granularity varchar(32),
    title varchar(255),
    latest_message varchar(2000),
    severity varchar(32),
    system_severity varchar(32),
    manual_severity varchar(32),
    status varchar(32),
    assignee_user_id bigint,
    assignee_name_snapshot varchar(255),
    first_seen_at datetime,
    last_seen_at datetime,
    last_recovery_at datetime,
    sla_due_at datetime,
    occurrence_count int default 0,
    consecutive_failure_count int default 0,
    reopen_count int default 0,
    last_run_record_id bigint,
    last_run_status varchar(32),
    current_evidence_json json,
    unique key uk_quality_issue_signature (tenant_id, project_id, signature(255)),
    key idx_quality_issue_status_severity (project_id, status, severity),
    key idx_quality_issue_asset (project_id, datasource_id, model_id),
    key idx_quality_issue_task (project_id, quality_task_id),
    key idx_quality_issue_last_seen (project_id, last_seen_at)
);

create table if not exists quality_issue_comment (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    issue_id bigint not null,
    author_user_id bigint,
    author_name_snapshot varchar(255),
    content text,
    key idx_quality_issue_comment_issue (issue_id, created_at)
);

create table if not exists quality_issue_event (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    issue_id bigint not null,
    event_type varchar(64),
    event_title varchar(255),
    event_message text,
    actor_user_id bigint,
    actor_name_snapshot varchar(255),
    metadata_json json,
    key idx_quality_issue_event_issue (issue_id, created_at),
    key idx_quality_issue_event_project_type (project_id, event_type, created_at)
);

create table if not exists quality_metric_snapshot (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    snapshot_date date,
    datasource_id bigint,
    datasource_name_snapshot varchar(255),
    datasource_type_code varchar(128),
    model_id bigint,
    model_name_snapshot varchar(255),
    model_physical_locator varchar(500),
    rule_dimension varchar(64),
    execution_health_score bigint,
    governance_risk_score bigint,
    active_issue_count bigint,
    overdue_issue_count bigint,
    coverage_rate bigint,
    failure_rate bigint,
    affected_asset_count bigint,
    reopen_rate bigint,
    key idx_quality_metric_snapshot_project_date (project_id, snapshot_date),
    key idx_quality_metric_snapshot_asset (project_id, datasource_id, model_id, snapshot_date),
    key idx_quality_metric_snapshot_dimension (project_id, rule_dimension, snapshot_date)
);

create table if not exists data_service_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    runtime_cluster_id bigint,
    service_code varchar(128) not null,
    service_name varchar(255) not null,
    service_type varchar(64) not null,
    status varchar(64) not null,
    source_type varchar(64) not null,
    datasource_id bigint,
    datasource_name_snapshot varchar(255),
    datasource_type_code varchar(128),
    model_id bigint,
    model_name_snapshot varchar(255),
    model_physical_locator varchar(1000),
    custom_sql longtext,
    request_method varchar(32),
    response_type varchar(32),
    endpoint_path varchar(1000),
    service_key varchar(128),
    cache_enabled int default 0,
    token_required int default 1,
    default_subscription_name varchar(255),
    webservice_enabled int default 0,
    webservice_config_json json,
    unique key uk_data_service_project_code (tenant_id, project_id, service_code),
    key idx_data_service_project_status (project_id, status),
    key idx_data_service_code_key (service_code, service_key)
);

create table if not exists data_service_request_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    sort_order int,
    param_name varchar(128) not null,
    field_name varchar(255),
    value_type varchar(64),
    query_operator varchar(64),
    required int default 0,
    description varchar(1000),
    fixed_param int default 0,
    key idx_data_service_request_service_order (service_id, sort_order)
);

create table if not exists data_service_response_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    sort_order int,
    enabled int default 1,
    param_name varchar(128) not null,
    field_name varchar(255) not null,
    example_value varchar(1000),
    description varchar(1000),
    transformers_json json,
    key idx_data_service_response_service_order (service_id, sort_order)
);

create table if not exists data_service_publish_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    sort_order int,
    frontend_param_name varchar(128) not null,
    backend_param_name varchar(128) not null,
    position varchar(32),
    value_type varchar(64),
    example_value varchar(1000),
    default_value varchar(1000),
    required int default 0,
    description varchar(1000),
    key idx_data_service_publish_service_order (service_id, sort_order)
);

create table if not exists data_service_subscription (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    subscription_name varchar(255) not null,
    token_hash varchar(128) not null,
    token_masked varchar(64),
    enabled int default 1,
    active_subscription_name varchar(255) generated always as (case when enabled = 1 then subscription_name else null end) stored,
    created_by bigint,
    last_used_at datetime,
    rotated_at datetime,
    rotated_by bigint,
    unique key uk_data_service_sub_active_name (service_id, active_subscription_name),
    key idx_data_service_subscription_service_enabled (service_id, enabled),
    key idx_data_service_subscription_token (token_hash)
);

create table if not exists data_service_access_log (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint,
    requested_cluster_id bigint,
    actual_cluster_id bigint,
    service_code_snapshot varchar(255),
    service_name_snapshot varchar(255),
    service_status_snapshot varchar(64),
    subscription_id bigint,
    subscription_name_snapshot varchar(255),
    request_id varchar(128),
    request_method varchar(16),
    occurred_at datetime,
    duration_ms bigint,
    success int default 0,
    http_status int,
    error_code varchar(128),
    error_message varchar(1000),
    system_log mediumtext,
    client_ip varchar(128),
    user_agent varchar(500),
    cache_enabled int default 0,
    cache_hit int default 0,
    row_count bigint default 0,
    log_storage_type varchar(64),
    log_object_bucket varchar(255),
    log_object_key varchar(1000),
    log_size_bytes bigint,
    log_charset varchar(64),
    log_archive_status varchar(64),
    log_archive_error varchar(1000),
    key idx_data_service_access_project_time (tenant_id, project_id, occurred_at),
    key idx_data_service_access_service_time (service_id, occurred_at),
    key idx_data_service_access_subscription_time (subscription_id, occurred_at),
    key idx_data_service_access_success (project_id, success, occurred_at),
    key idx_data_service_access_cache (project_id, cache_hit, occurred_at)
);

create table if not exists data_service_access_counter (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null default 0,
    subscription_id bigint not null default 0,
    bucket_start datetime not null,
    success int not null default 0,
    cache_enabled int not null default 0,
    cache_hit int not null default 0,
    access_count bigint default 0,
    row_count bigint default 0,
    unique key uk_data_service_access_counter (tenant_id, project_id, service_id, subscription_id, bucket_start, success, cache_enabled, cache_hit),
    key idx_data_service_counter_project_bucket (tenant_id, project_id, bucket_start),
    key idx_data_service_counter_service_bucket (service_id, bucket_start)
);

create table if not exists data_ingestion_service (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    runtime_cluster_id bigint,
    service_code varchar(128) not null,
    service_name varchar(255) not null,
    status varchar(64) not null,
    request_format varchar(32) not null,
    payload_mode varchar(32),
    data_node_path varchar(500),
    target_type varchar(32) not null,
    datasource_id bigint,
    datasource_name_snapshot varchar(255),
    datasource_type_code varchar(128),
    model_id bigint,
    model_name_snapshot varchar(255),
    model_physical_locator varchar(1000),
    endpoint_path varchar(1000),
    service_key varchar(128),
    max_batch_size int default 500,
    token_required int default 1,
    default_subscription_name varchar(255),
    webservice_enabled int default 0,
    webservice_config_json json,
    writer_options_json json,
    field_mappings_json json,
    source_positions_json json,
    source_bindings_json json,
    source_count int default 1,
    target_count int default 1,
    unique key uk_data_ingestion_project_code (tenant_id, project_id, service_code),
    key idx_data_ingestion_project_status (project_id, status),
    key idx_data_ingestion_code_key (service_code, service_key)
);

create table if not exists data_ingestion_subscription (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    subscription_name varchar(255) not null,
    token_hash varchar(128) not null,
    token_masked varchar(64),
    enabled int default 1,
    active_subscription_name varchar(255) generated always as (case when enabled = 1 then subscription_name else null end) stored,
    created_by bigint,
    last_used_at datetime,
    rotated_at datetime,
    rotated_by bigint,
    unique key uk_data_ingestion_sub_active_name (service_id, active_subscription_name),
    key idx_data_ingestion_sub_service_enabled (service_id, enabled),
    key idx_data_ingestion_sub_token (token_hash)
);

create table if not exists data_ingestion_access_log (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint,
    requested_cluster_id bigint,
    actual_cluster_id bigint,
    service_code_snapshot varchar(255),
    service_name_snapshot varchar(255),
    service_status_snapshot varchar(64),
    subscription_id bigint,
    subscription_name_snapshot varchar(255),
    request_id varchar(128),
    request_method varchar(16),
    occurred_at datetime,
    duration_ms bigint,
    success int default 0,
    http_status int,
    error_code varchar(128),
    error_message varchar(1000),
    system_log mediumtext,
    client_ip varchar(128),
    user_agent varchar(500),
    received_count bigint default 0,
    success_count bigint default 0,
    failed_count bigint default 0,
    log_storage_type varchar(64),
    log_object_bucket varchar(255),
    log_object_key varchar(1000),
    log_size_bytes bigint,
    log_charset varchar(64),
    log_archive_status varchar(64),
    log_archive_error varchar(1000),
    key idx_data_ingestion_access_project_time (tenant_id, project_id, occurred_at),
    key idx_data_ingestion_access_service_time (service_id, occurred_at),
    key idx_data_ingestion_access_subscription_time (subscription_id, occurred_at),
    key idx_data_ingestion_access_success (project_id, success, occurred_at)
);

create table if not exists data_ingestion_access_counter (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null default 0,
    subscription_id bigint not null default 0,
    bucket_start datetime not null,
    success int not null default 0,
    access_count bigint default 0,
    received_count bigint default 0,
    success_count bigint default 0,
    failed_count bigint default 0,
    unique key uk_data_ingestion_access_counter (tenant_id, project_id, service_id, subscription_id, bucket_start, success),
    key idx_data_ingestion_counter_project_bucket (tenant_id, project_id, bucket_start),
    key idx_data_ingestion_counter_service_bucket (service_id, bucket_start)
);

create table if not exists protocol_conversion_service (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    runtime_cluster_id bigint,
    service_code varchar(128) not null,
    service_name varchar(255) not null,
    status varchar(64) not null,
    endpoint_path varchar(1000),
    webservice_endpoint_path varchar(1000),
    service_key varchar(128),
    token_required int default 1,
    default_subscription_name varchar(255),
    source_protocol varchar(32) not null,
    source_method varchar(16),
    source_data_node_path varchar(500),
    webservice_config_json json,
    conversion_mode varchar(32) not null,
    field_mappings_json json,
    raw_transformers_json json,
    fixed_fields_json json,
    body_bridge_options_json json,
    request_passthrough_json json,
    target_datasource_id bigint,
    target_datasource_name_snapshot varchar(255),
    target_path varchar(1000),
    target_protocol varchar(32) not null,
    target_method varchar(16),
    target_headers_json json,
    target_query_json json,
    target_webservice_config_json json,
    target_body_template mediumtext,
    target_data_node_path varchar(500),
    payload_mode varchar(32),
    batch_size int default 1,
    response_status_json json,
    unique key uk_protocol_conversion_project_code (tenant_id, project_id, service_code),
    key idx_protocol_conversion_project_status (project_id, status),
    key idx_protocol_conversion_code_key (service_code, service_key)
);

create table if not exists protocol_conversion_subscription (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    subscription_name varchar(255) not null,
    token_hash varchar(128) not null,
    token_masked varchar(64),
    enabled int default 1,
    active_subscription_name varchar(255) generated always as (case when enabled = 1 then subscription_name else null end) stored,
    created_by bigint,
    last_used_at datetime,
    rotated_at datetime,
    rotated_by bigint,
    unique key uk_protocol_conversion_sub_active_name (service_id, active_subscription_name),
    key idx_protocol_conversion_sub_service_enabled (service_id, enabled),
    key idx_protocol_conversion_sub_token (token_hash)
);

create table if not exists protocol_conversion_access_log (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint,
    requested_cluster_id bigint,
    actual_cluster_id bigint,
    service_code_snapshot varchar(255),
    service_name_snapshot varchar(255),
    service_status_snapshot varchar(64),
    subscription_id bigint,
    subscription_name_snapshot varchar(255),
    request_id varchar(128),
    request_method varchar(16),
    source_protocol_snapshot varchar(32),
    target_protocol_snapshot varchar(32),
    occurred_at datetime,
    duration_ms bigint,
    success int default 0,
    http_status int,
    target_http_status int,
    error_code varchar(128),
    error_message varchar(1000),
    system_log mediumtext,
    client_ip varchar(128),
    user_agent varchar(500),
    received_count bigint default 0,
    success_count bigint default 0,
    failed_count bigint default 0,
    log_storage_type varchar(64),
    log_object_bucket varchar(255),
    log_object_key varchar(1000),
    log_size_bytes bigint,
    log_charset varchar(64),
    log_archive_status varchar(64),
    log_archive_error varchar(1000),
    key idx_protocol_conversion_access_project_time (tenant_id, project_id, occurred_at),
    key idx_protocol_conversion_access_service_time (service_id, occurred_at),
    key idx_protocol_conversion_access_subscription_time (subscription_id, occurred_at),
    key idx_protocol_conversion_access_success (project_id, success, occurred_at)
);

create table if not exists protocol_conversion_access_counter (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null default 0,
    subscription_id bigint not null default 0,
    bucket_start datetime not null,
    success int not null default 0,
    access_count bigint default 0,
    received_count bigint default 0,
    success_count bigint default 0,
    failed_count bigint default 0,
    unique key uk_protocol_conversion_access_counter (tenant_id, project_id, service_id, subscription_id, bucket_start, success),
    key idx_protocol_conversion_counter_project_bucket (tenant_id, project_id, bucket_start),
    key idx_protocol_conversion_counter_service_bucket (service_id, bucket_start)
);

create table if not exists data_dev_directory (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    parent_id bigint,
    name varchar(255),
    permission_code varchar(255),
    description varchar(1000),
    key idx_data_dev_directory_project_parent (project_id, parent_id),
    key idx_data_dev_directory_parent (parent_id)
);

create table if not exists data_dev_script (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    directory_id bigint,
    runtime_cluster_id bigint,
    file_name varchar(255),
    script_type varchar(64),
    datasource_id bigint,
    environment_id bigint,
    description varchar(1000),
    execution_config_json json,
    content longtext,
    key idx_data_dev_script_project_directory (project_id, directory_id),
    key idx_data_dev_script_directory (directory_id),
    key idx_data_dev_script_datasource (datasource_id),
    key idx_data_dev_script_environment (environment_id)
);

create table if not exists so_pf_artifact_store (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    store_name varchar(255) not null,
    store_code varchar(64) not null,
    provider varchar(32) not null,
    scope_type varchar(32) default 'TENANT',
    config_version bigint default 1,
    endpoint varchar(1000) not null,
    upload_url varchar(1000),
    simple_index_url varchar(1000),
    bucket varchar(255),
    region varchar(128),
    root_prefix varchar(512),
    username_ciphertext text,
    secret_ciphertext text,
    verify_ssl int default 1,
    enabled int default 1,
    description text,
    unique key uk_so_pf_artifact_store_code (tenant_id, store_code),
    key idx_so_pf_artifact_store_provider (tenant_id, scope_type, provider, enabled)
);

create table if not exists so_pf_env_dep (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    name varchar(255) not null,
    version varchar(128),
    script_type varchar(32) default 'JAVA',
    artifact_store_id bigint,
    artifact_url text,
    artifact_type varchar(32),
    checksum varchar(128),
    enabled int default 1,
    description text,
    key idx_so_pf_env_dep_tenant_enabled (tenant_id, enabled),
    unique key uk_so_pf_env_dep_name_ver (tenant_id, name, version)
);

create table if not exists so_pf_env_dep_file (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    dependency_id bigint not null,
    original_file_name varchar(512) not null,
    artifact_type varchar(32) not null,
    object_key text,
    object_url text,
    checksum varchar(128),
    size_bytes bigint,
    visible int default 1,
    runtime_artifact int default 0,
    source_file_id bigint,
    enabled int default 1,
    key idx_so_pf_env_dep_file_dep (tenant_id, dependency_id, visible),
    key idx_so_pf_env_dep_file_runtime (tenant_id, dependency_id, runtime_artifact)
);

create table if not exists so_pf_script_env (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    environment_name varchar(255) not null,
    environment_code varchar(128) not null,
    enabled int default 1,
    use_application_parent int default 1,
    environment_version bigint default 1,
    python_install_mode varchar(32) default 'LOCAL_ARTIFACT',
    python_repository_id bigint,
    description text,
    unique key uk_so_pf_script_env_code (tenant_id, environment_code),
    key idx_so_pf_script_env_enabled (tenant_id, enabled)
);

create table if not exists so_pf_env_dep_rel (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    environment_id bigint not null,
    dependency_id bigint not null,
    sort_order int default 0,
    key idx_so_pf_env_dep_rel_env (environment_id, sort_order),
    unique key uk_so_pf_env_dep_rel (environment_id, dependency_id)
);

create table if not exists dispatch_task (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    execution_type varchar(64),
    workflow_run_id bigint,
    workflow_definition_id bigint,
    workflow_version_id bigint,
    collection_task_id bigint,
    quality_task_id bigint,
    file_transfer_task_id bigint,
    file_transfer_run_id bigint,
    triggered_by_user_id bigint,
    run_record_id bigint,
    node_code varchar(255),
    status varchar(64),
    termination_requested int default 0,
    target_cluster_id bigint,
    resource_revision varchar(128),
    claim_token varchar(64),
    worker_boot_id varchar(128),
    worker_group_code varchar(255),
    lease_owner varchar(255),
    worker_instance_id varchar(255),
    lease_expires_at datetime,
    scheduled_fire_time datetime,
    attempts int default 0,
    max_retries int default 3,
    protected_payload_ciphertext mediumtext,
    payload_json json,
    key idx_dispatch_task_project_status (project_id, status),
    key idx_dispatch_task_project_workflow_run (project_id, workflow_run_id),
    key idx_dispatch_task_project_quality_task_status (project_id, quality_task_id, status),
    key idx_dispatch_task_file_transfer_run (file_transfer_run_id, status),
    key idx_dispatch_task_project_status_created (project_id, status, created_at),
    key idx_dispatch_task_group_status_created (worker_group_code, status, created_at),
    key idx_dispatch_task_cluster_status_created (target_cluster_id, status, created_at),
    key idx_dispatch_task_termination_status (termination_requested, status, worker_instance_id)
);

create table if not exists run_record (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    execution_type varchar(64),
    workflow_run_id bigint,
    workflow_definition_id bigint,
    workflow_version_id bigint,
    collection_task_id bigint,
    quality_task_id bigint,
    file_transfer_task_id bigint,
    file_transfer_run_id bigint,
    triggered_by_user_id bigint,
    node_code varchar(255),
    status varchar(64),
    termination_requested int default 0,
    requested_cluster_id bigint,
    actual_cluster_id bigint,
    actual_cluster_code varchar(64),
    worker_group_code varchar(255),
    worker_code varchar(255),
    worker_instance_id varchar(255),
    worker_boot_id varchar(128),
    worker_pod_name varchar(255),
    worker_node_name varchar(255),
    message varchar(2000),
    started_at datetime,
    ended_at datetime,
    collected_records bigint,
    read_succeed_records bigint,
    read_failed_records bigint,
    write_succeed_records bigint,
    write_failed_records bigint,
    failed_records bigint,
    success_records bigint,
    transformer_total_records bigint,
    transformer_success_records bigint,
    transformer_failed_records bigint,
    transformer_filter_records bigint,
    log_file_path varchar(1000),
    log_size_bytes bigint,
    log_charset varchar(64),
    log_storage_type varchar(64),
    log_object_bucket varchar(255),
    log_object_key varchar(1000),
    log_chunk_count int,
    log_status varchar(64),
    log_error_summary varchar(1000),
    payload_json json,
    result_json json,
    key idx_run_record_project_created (project_id, created_at),
    key idx_run_record_project_workflow_run (project_id, workflow_run_id),
    key idx_run_record_project_collection_task_ended (project_id, collection_task_id, ended_at),
    key idx_run_record_project_quality_task_ended (project_id, quality_task_id, ended_at),
    key idx_run_record_file_transfer_run (file_transfer_run_id),
    key idx_run_record_project_cluster_created (project_id, requested_cluster_id, created_at),
    key idx_run_record_termination_status (termination_requested, status, worker_instance_id)
);

create table if not exists file_transfer_task_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    name varchar(255) not null,
    code varchar(128) not null,
    status varchar(32) not null,
    version int not null default 1,
    published_version int,
    runtime_cluster_id bigint,
    source_runtime_cluster_id bigint not null,
    source_datasource_id bigint not null,
    source_datasource_name_snapshot varchar(255),
    source_datasource_type_snapshot varchar(128),
    target_runtime_cluster_id bigint not null,
    target_datasource_id bigint not null,
    target_datasource_name_snapshot varchar(255),
    target_datasource_type_snapshot varchar(128),
    selection_json json,
    mapping_json json,
    policy_json json,
    runtime_json json,
    published_snapshot_json json,
    schedule_enabled int default 0,
    cron_expression varchar(255),
    timezone varchar(64),
    last_triggered_at datetime,
    unique key uk_ft_task_project_code (tenant_id, project_id, code),
    key idx_ft_task_project_status (project_id, status),
    key idx_ft_task_schedule (status, schedule_enabled, last_triggered_at)
);

create table if not exists file_transfer_run (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    run_record_id bigint,
    task_id bigint,
    task_name_snapshot varchar(255),
    trigger_type varchar(32),
    direction varchar(32),
    channel varchar(32),
    status varchar(32) not null,
    queue_visible int not null default 1,
    runtime_cluster_id bigint,
    source_runtime_cluster_id bigint,
    source_datasource_id bigint,
    target_runtime_cluster_id bigint not null,
    target_datasource_id bigint,
    total_files bigint default 0,
    success_files bigint default 0,
    skipped_files bigint default 0,
    failed_files bigint default 0,
    conflict_files bigint default 0,
    resumed_files bigint default 0,
    post_action_failed_files bigint default 0,
    total_bytes bigint default 0,
    transferred_bytes bigint default 0,
    failed_bytes bigint default 0,
    resumed_bytes bigint default 0,
    current_bytes_per_second bigint default 0,
    peak_bytes_per_second bigint default 0,
    active_files int default 0,
    retry_count int default 0,
    message varchar(2000),
    started_at datetime,
    ended_at datetime,
    resolved_spec_json json,
    unique key uk_ft_run_record (run_record_id),
    key idx_ft_run_project_created (project_id, created_at),
    key idx_ft_run_task_status (task_id, status),
    key idx_ft_run_target_status (target_runtime_cluster_id, status)
);

create table if not exists file_transfer_run_item (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    run_id bigint not null,
    core_item_id varchar(64) not null,
    direction varchar(32),
    channel varchar(32),
    runtime_cluster_id bigint,
    source_runtime_cluster_id bigint not null,
    source_datasource_id bigint not null,
    source_path varchar(2000) not null,
    target_runtime_cluster_id bigint not null,
    target_datasource_id bigint not null,
    target_path varchar(2000) not null,
    temporary_path varchar(2000),
    status varchar(32) not null,
    file_size bigint default 0,
    transferred_bytes bigint default 0,
    resumed_bytes bigint default 0,
    current_bytes_per_second bigint default 0,
    source_checksum varchar(128),
    target_checksum varchar(128),
    attempts int default 0,
    error_code varchar(128),
    error_message varchar(2000),
    conflict_action varchar(32),
    source_action varchar(32),
    post_action_status varchar(32),
    started_at datetime,
    ended_at datetime,
    source_snapshot_json json,
    checkpoint_json json,
    unique key uk_ft_item_run_core (run_id, core_item_id),
    key idx_ft_item_run_status (run_id, status),
    key idx_ft_item_project_updated (project_id, updated_at)
);

create table if not exists file_transfer_metric_sample (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    run_id bigint not null,
    run_record_id bigint,
    task_id bigint,
    runtime_cluster_id bigint,
    source_datasource_id bigint,
    target_datasource_id bigint,
    channel varchar(32),
    status varchar(32),
    sampled_at datetime not null,
    transferred_bytes bigint default 0,
    bytes_per_second bigint default 0,
    completed_files bigint default 0,
    failed_files bigint default 0,
    active_files int default 0,
    retry_count int default 0,
    key idx_ft_metric_project_time (project_id, sampled_at),
    key idx_ft_metric_run_time (run_id, sampled_at),
    key idx_ft_metric_task_time (task_id, sampled_at)
);

create table if not exists file_transfer_event_outbox (
    id bigint primary key,
    tenant_id varchar(64) not null,
    project_id bigint not null,
    deleted int not null default 0,
    created_at datetime not null default current_timestamp,
    updated_at datetime not null default current_timestamp,
    event_type varchar(32) not null,
    run_id bigint not null,
    item_id bigint,
    occurred_at datetime not null,
    payload_version int not null default 1,
    payload_json json,
    key idx_ft_outbox_scope_id (tenant_id, project_id, id),
    key idx_ft_outbox_run_id (run_id, id),
    key idx_ft_outbox_created (created_at, id),
    key idx_ft_outbox_event_type (event_type, created_at, id)
);

create table if not exists file_transfer_event_consumer_cursor (
    id bigint primary key,
    instance_id varchar(255) not null,
    tenant_id varchar(64) not null,
    project_id bigint not null,
    last_event_id bigint not null default 0,
    last_seen_at datetime not null,
    created_at datetime not null default current_timestamp,
    updated_at datetime not null default current_timestamp,
    unique key uk_ft_event_cursor_scope (instance_id, tenant_id, project_id),
    key idx_ft_event_cursor_seen (instance_id, last_seen_at),
    key idx_ft_event_cursor_position (tenant_id, project_id, last_event_id)
);

create table if not exists data_model_lineage_relation (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    level varchar(32),
    source_type varchar(64),
    collection_task_id bigint,
    collection_task_name_snapshot varchar(255),
    source_datasource_id bigint,
    source_datasource_name_snapshot varchar(255),
    source_datasource_type_snapshot varchar(128),
    source_database_name_snapshot varchar(255),
    source_host_snapshot varchar(255),
    source_port_snapshot varchar(64),
    source_model_id bigint,
    source_model_name_snapshot varchar(255),
    source_model_locator_snapshot varchar(1000),
    source_field_key varchar(255),
    target_datasource_id bigint,
    target_datasource_name_snapshot varchar(255),
    target_datasource_type_snapshot varchar(128),
    target_database_name_snapshot varchar(255),
    target_host_snapshot varchar(255),
    target_port_snapshot varchar(64),
    target_model_id bigint,
    target_model_name_snapshot varchar(255),
    target_model_locator_snapshot varchar(1000),
    target_field_key varchar(255),
    mapping_mode varchar(64),
    expression_snapshot text,
    manual_maintainer_user_id bigint,
    manual_maintainer_name_snapshot varchar(255),
    latest_run_id bigint,
    latest_run_status varchar(64),
    latest_run_at datetime,
    key idx_data_model_lineage_target_level (tenant_id, target_model_id, level),
    key idx_data_model_lineage_source_level (tenant_id, source_model_id, level),
    key idx_data_model_lineage_task (tenant_id, collection_task_id),
    key idx_data_model_lineage_target_datasource_level (tenant_id, target_datasource_id, level),
    key idx_data_model_lineage_source_datasource_level (tenant_id, source_datasource_id, level)
);

create table if not exists worker_lease (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    runtime_cluster_id bigint,
    runtime_cluster_code varchar(64),
    worker_group_code varchar(255),
    worker_code varchar(255),
    worker_kind varchar(64),
    instance_id varchar(255),
    boot_id varchar(128),
    runtime_version varchar(128),
    plugin_fingerprint varchar(128),
    host_name varchar(255),
    pod_name varchar(255),
    node_name varchar(255),
    status varchar(64),
    last_heartbeat_at datetime,
    lease_expires_at datetime,
    capabilities_json json,
    key idx_worker_lease_code_instance (worker_code, instance_id),
    key idx_worker_lease_group_instance (worker_group_code, instance_id),
    key idx_worker_lease_status_heartbeat (status, last_heartbeat_at),
    key idx_worker_lease_cluster_status (runtime_cluster_id, status, last_heartbeat_at)
);

create table if not exists studio_cluster_lock (
    id bigint primary key,
    lock_name varchar(255) not null,
    owner_id varchar(255),
    locked_until datetime,
    last_acquired_at datetime,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    unique key uk_studio_cluster_lock_name (lock_name),
    key idx_studio_cluster_lock_until (locked_until)
);

create table if not exists studio_alert_rule (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    name varchar(255) not null,
    active_name varchar(255) generated always as (case when deleted = 0 then name else null end) stored,
    description text,
    rule_type varchar(64) not null,
    subject_type varchar(64) not null,
    subject_id bigint,
    subject_name_snapshot varchar(255),
    severity varchar(32) not null,
    enabled int default 0,
    condition_json json,
    silence_minutes int default 30,
    recovery_notification_enabled int default 1,
    in_app_enabled int default 1,
    recipient_user_ids_json json,
    notify_resource_owner int default 0,
    notify_project_admins int default 1,
    webhook_channel_ids_json json,
    activation_at datetime,
    last_evaluated_at datetime,
    last_evaluation_status varchar(32),
    last_evaluation_error varchar(1000),
    last_triggered_at datetime,
    created_by bigint,
    updated_by bigint,
    unique key uk_alert_rule_active_name (tenant_id, project_id, active_name),
    key idx_alert_rule_project_enabled (project_id, enabled, rule_type),
    key idx_alert_rule_project_name (project_id, name)
);

create table if not exists studio_alert_incident (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    rule_id bigint not null,
    rule_name_snapshot varchar(255),
    rule_type varchar(64),
    signature varchar(64) not null,
    subject_type varchar(64),
    subject_key varchar(255),
    subject_id bigint,
    subject_name_snapshot varchar(255),
    target_path varchar(1000),
    severity varchar(32),
    status varchar(32),
    summary varchar(1000),
    requested_cluster_id bigint,
    actual_cluster_id bigint,
    current_evidence_json json,
    occurrence_count int default 0,
    notification_count int default 0,
    reopen_count int default 0,
    condition_active int default 0,
    closed_while_active int default 0,
    first_triggered_at datetime,
    last_triggered_at datetime,
    last_notified_at datetime,
    acknowledged_at datetime,
    recovered_at datetime,
    closed_at datetime,
    acknowledged_by bigint,
    closed_by bigint,
    version int default 0,
    unique key uk_alert_incident_signature (tenant_id, project_id, signature),
    key idx_alert_incident_status (project_id, status, severity, last_triggered_at),
    key idx_alert_incident_rule (rule_id, last_triggered_at),
    key idx_alert_incident_subject (project_id, subject_type, subject_id),
    key idx_alert_incident_cluster (project_id, requested_cluster_id, actual_cluster_id, last_triggered_at)
);

create table if not exists studio_alert_event (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    incident_id bigint,
    rule_id bigint,
    event_type varchar(32) not null,
    status_from varchar(32),
    status_to varchar(32),
    source_type varchar(64),
    source_id varchar(255),
    source_event_key varchar(255) not null,
    subject_type varchar(64),
    subject_key varchar(255),
    subject_id bigint,
    subject_name_snapshot varchar(255),
    target_path varchar(1000),
    severity varchar(32),
    summary varchar(1000),
    evidence_json json,
    actor_user_id bigint,
    actor_name_snapshot varchar(255),
    observed_at datetime,
    unique key uk_alert_event_source (tenant_id, project_id, source_event_key),
    key idx_alert_event_incident (incident_id, observed_at),
    key idx_alert_event_rule (rule_id, event_type, observed_at)
);

create table if not exists studio_alert_channel (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    name varchar(255) not null,
    active_name varchar(255) generated always as (case when deleted = 0 then name else null end) stored,
    channel_type varchar(32) not null,
    endpoint_ciphertext text,
    headers_ciphertext text,
    signing_secret_ciphertext text,
    config_json json,
    enabled int default 1,
    last_tested_at datetime,
    last_test_status varchar(32),
    last_test_message varchar(1000),
    created_by bigint,
    updated_by bigint,
    unique key uk_alert_channel_active_name (tenant_id, project_id, active_name),
    key idx_alert_channel_project_enabled (project_id, enabled),
    key idx_alert_channel_project_name (project_id, name)
);

create table if not exists studio_alert_delivery (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    event_id bigint not null,
    incident_id bigint,
    delivery_key varchar(255) not null,
    channel_type varchar(32) not null,
    channel_id bigint,
    channel_name_snapshot varchar(255),
    recipient_user_id bigint,
    status varchar(32) not null,
    attempt_count int default 0,
    next_attempt_at datetime,
    last_attempt_at datetime,
    http_status int,
    response_excerpt varchar(2000),
    error_message varchar(1000),
    payload_json json,
    unique key uk_alert_delivery_event_key (event_id, delivery_key),
    key idx_alert_delivery_due (status, next_attempt_at),
    key idx_alert_delivery_channel (channel_id, created_at),
    key idx_alert_delivery_incident (incident_id, created_at)
);
