create table if not exists sys_user (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    username varchar(128) not null,
    password_hash varchar(255) not null,
    display_name varchar(255),
    enabled int default 1,
    auth_source varchar(32) default 'LOCAL',
    unique key uk_sys_user_username (username)
);

create table if not exists studio_external_user_binding (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    provider_code varchar(64) not null,
    external_user_id varchar(128) not null,
    external_account varchar(255),
    studio_user_id bigint not null,
    last_seen_at datetime,
    unique key uk_studio_external_user_binding_external (provider_code, external_user_id),
    key idx_studio_external_user_binding_user (studio_user_id)
);

create table if not exists sys_role (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    code varchar(128) not null,
    name varchar(255) not null,
    description varchar(500),
    unique key uk_sys_role_code (code)
);

create table if not exists sys_permission (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    code varchar(128) not null,
    name varchar(255) not null,
    http_method varchar(32),
    path_pattern varchar(255),
    unique key uk_sys_permission_code (code)
);

create table if not exists sys_user_role (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    user_id bigint not null,
    role_id bigint not null
);

create table if not exists sys_role_permission (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    role_id bigint not null,
    permission_id bigint not null
);

create table if not exists studio_tenant (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    tenant_code varchar(64) not null,
    tenant_name varchar(255) not null,
    description varchar(1000),
    enabled int default 1,
    unique key uk_studio_tenant_code (tenant_code)
);

create table if not exists studio_project (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    project_code varchar(128) not null,
    project_name varchar(255) not null,
    description varchar(1000),
    enabled int default 1,
    default_project int default 0,
    unique key uk_studio_project_code (tenant_id, project_code),
    unique key uk_studio_project_name (tenant_id, project_name)
);

create table if not exists studio_tenant_member (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    user_id bigint not null,
    role_code varchar(128) not null,
    status varchar(64) not null,
    unique key uk_studio_tenant_member_user (tenant_id, user_id)
);

create table if not exists studio_project_member (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    project_id bigint not null,
    user_id bigint not null,
    role_code varchar(128) not null,
    status varchar(64) not null,
    unique key uk_studio_project_member_user (project_id, user_id)
);

create table if not exists studio_project_member_request (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    project_id bigint not null,
    user_id bigint not null,
    request_type varchar(64) not null,
    status varchar(64) not null,
    inviter_user_id bigint,
    reviewer_user_id bigint,
    reason varchar(1000),
    review_comment varchar(1000),
    key idx_studio_project_member_request_lookup (project_id, user_id, status)
);

create table if not exists studio_project_worker_binding (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    project_id bigint not null,
    worker_group_code varchar(255),
    worker_code varchar(255) not null,
    enabled int default 1,
    unique key uk_studio_project_worker_binding (project_id, worker_code),
    key idx_studio_project_worker_group (project_id, worker_group_code)
);

create table if not exists studio_resource_share (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    source_project_id bigint not null,
    target_project_id bigint not null,
    resource_type varchar(128) not null,
    resource_id bigint not null,
    shared_by_user_id bigint,
    enabled int default 1,
    unique key uk_studio_resource_share_target (resource_type, resource_id, target_project_id),
    key idx_studio_resource_share_project (target_project_id)
);

create table if not exists datasource_type_capability (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    type_code varchar(128) not null,
    type_name varchar(255) not null,
    enabled int default 1,
    readable int default 0,
    writable int default 0,
    executable int default 0,
    sql_executable int default 0,
    source_category varchar(32) not null default 'DATABASE',
    source_plugin varchar(128),
    reader_plugins_json json,
    writer_plugins_json json,
    sort_order int default 0,
    description varchar(1000),
    unique key uk_datasource_type_capability_code (tenant_id, type_code)
);

create table if not exists field_mapping_rule (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    mapping_name varchar(255) not null,
    mapping_type varchar(255) not null,
    mapping_code varchar(255) not null,
    enabled int default 1,
    description varchar(1000),
    created_by bigint,
    unique key uk_field_mapping_rule_code (mapping_code),
    key idx_field_mapping_rule_type_enabled (mapping_type, enabled),
    key idx_field_mapping_rule_created_at (created_at)
);

create table if not exists field_mapping_rule_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    rule_id bigint not null,
    param_name varchar(255) not null,
    param_order int not null,
    component_type varchar(64) not null,
    param_value_json text,
    description varchar(1000),
    key idx_field_mapping_rule_param_rule_order (rule_id, param_order),
    key idx_field_mapping_rule_param_rule_name (rule_id, param_name)
);

create table if not exists quality_rule (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    rule_name varchar(255) not null,
    rule_code varchar(255) not null,
    scope_type varchar(32) not null,
    rule_dimension varchar(64) not null,
    description varchar(2000),
    supported_datasource_types_json json,
    granularity varchar(32) not null,
    logic_sql text,
    enabled int default 1,
    unique key uk_quality_rule_scope_code (tenant_id, project_id, scope_type, rule_code),
    key idx_quality_rule_scope_enabled (tenant_id, project_id, scope_type, enabled),
    key idx_quality_rule_dimension_enabled (rule_dimension, enabled)
);

create table if not exists quality_rule_input_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    rule_id bigint not null,
    param_order int not null,
    param_name varchar(255) not null,
    param_type varchar(32) not null,
    param_meaning varchar(1000),
    key idx_quality_rule_input_param_rule_order (rule_id, param_order),
    key idx_quality_rule_input_param_rule_name (rule_id, param_name)
);

create table if not exists quality_rule_output_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    rule_id bigint not null,
    output_order int not null,
    result_field varchar(255) not null,
    output_type varchar(32) not null,
    output_description varchar(1000),
    key idx_quality_rule_output_param_rule_order (rule_id, output_order),
    key idx_quality_rule_output_param_rule_field (rule_id, result_field)
);

create table if not exists user_registration_request (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    status varchar(64) not null,
    username varchar(128) not null,
    password_hash varchar(255) not null,
    display_name varchar(255),
    reason varchar(1000),
    review_comment varchar(1000),
    reviewer_user_id bigint,
    approved_user_id bigint,
    reviewed_at datetime,
    key idx_user_registration_request_status_created (status, created_at),
    unique key uk_user_registration_request_username_status (username, status)
);

create table if not exists studio_notification (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    recipient_user_id bigint not null,
    tenant_id varchar(64),
    project_id bigint,
    category varchar(128),
    title varchar(255),
    content varchar(2000),
    target_type varchar(128),
    target_id bigint,
    target_path varchar(1000),
    target_tenant_id varchar(64),
    target_project_id bigint,
    dedupe_key varchar(255),
    read_at datetime,
    archived_at datetime,
    payload_json json,
    key idx_studio_notification_recipient_created (recipient_user_id, created_at),
    key idx_studio_notification_recipient_unread (recipient_user_id, read_at, archived_at),
    unique key uk_studio_notification_recipient_dedupe (recipient_user_id, dedupe_key)
);

create table if not exists studio_follow_subscription (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    user_id bigint not null,
    target_type varchar(128) not null,
    target_id bigint not null,
    enabled int default 1,
    unique key uk_studio_follow_subscription_target (tenant_id, project_id, user_id, target_type, target_id),
    key idx_studio_follow_subscription_lookup (target_type, target_id, enabled)
);

create table if not exists meta_schema (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    schema_code varchar(255),
    schema_name varchar(255),
    object_type varchar(128),
    type_code varchar(255),
    current_version_id bigint,
    status varchar(64),
    description varchar(1000)
);

create table if not exists meta_schema_version (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    schema_id bigint,
    version_number int,
    status varchar(64),
    description varchar(1000)
);

create table if not exists meta_field_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    schema_version_id bigint,
    field_key varchar(255),
    field_name varchar(255),
    description varchar(1000),
    scope varchar(64),
    value_type varchar(64),
    component_type varchar(64),
    required_flag int default 0,
    sensitive_flag int default 0,
    sort_order int default 0,
    validation_rule varchar(1000),
    placeholder varchar(255),
    default_value varchar(1000),
    searchable_flag int default 0,
    sortable_flag int default 0,
    query_operators json,
    query_default_operator varchar(64),
    options json
);

create table if not exists datasource_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    name varchar(255),
    type_code varchar(128),
    schema_version_id bigint,
    enabled int default 1,
    executable int default 0,
    connection_status varchar(32) default 'UNKNOWN',
    last_connection_test_at datetime,
    last_connection_test_message varchar(1000),
    last_connection_test_duration_ms bigint,
    technical_metadata json,
    business_metadata json,
    unique key uk_datasource_definition_project_name (project_id, name),
    key idx_datasource_definition_project (project_id)
);

create table if not exists data_model (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    datasource_id bigint,
    name varchar(255),
    model_kind varchar(64),
    physical_locator varchar(1000),
    schema_version_id bigint,
    technical_metadata json,
    business_metadata json,
    unique key uk_data_model_project_datasource_name (project_id, datasource_id, name),
    key idx_data_model_project (project_id),
    key idx_data_model_tenant_project_created (tenant_id, project_id, created_at),
    key idx_data_model_tenant_datasource_created (tenant_id, datasource_id, created_at)
);

create table if not exists model_sync_task (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    datasource_id bigint not null,
    datasource_type varchar(128),
    datasource_name_snapshot varchar(255),
    batch_no int not null,
    name varchar(255) not null,
    source varchar(64),
    status varchar(64),
    total_count int default 0,
    success_count int default 0,
    failed_count int default 0,
    stopped_count int default 0,
    progress_percent int default 0,
    stop_requested int default 0,
    created_by bigint,
    started_at datetime,
    finished_at datetime,
    duration_ms bigint,
    last_error varchar(2000),
    unique key uk_model_sync_task_project_datasource_batch (project_id, datasource_id, batch_no),
    key idx_model_sync_task_project_created (project_id, created_at),
    key idx_model_sync_task_project_status (project_id, status)
);

create table if not exists model_sync_task_item (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    task_id bigint not null,
    seq_no int not null,
    physical_locator varchar(1000),
    model_name_snapshot varchar(255),
    status varchar(64),
    message varchar(2000),
    started_at datetime,
    finished_at datetime,
    duration_ms bigint,
    key idx_model_sync_task_item_task_seq (task_id, seq_no),
    key idx_model_sync_task_item_task_status (task_id, status)
);

create table if not exists data_model_attr_index (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    model_id bigint,
    datasource_id bigint,
    meta_schema_version_id bigint,
    meta_schema_code varchar(255),
    scope varchar(64),
    meta_model_code varchar(128),
    item_key varchar(255),
    field_key varchar(255),
    value_type varchar(64),
    keyword_value varchar(1000),
    text_value text,
    number_value decimal(38, 10),
    bool_value int,
    raw_value text,
    key idx_model_attr_index_project (project_id),
    key idx_model_attr_index_model (model_id),
    key idx_model_attr_index_tenant_model_item (tenant_id, model_id, item_key),
    key idx_model_attr_index_datasource (datasource_id),
    key idx_model_attr_index_lookup (meta_schema_code(128), scope, field_key(128), keyword_value(128)),
    key idx_model_attr_index_number (meta_schema_code, scope, field_key, number_value),
    key idx_model_attr_index_tenant_lookup (tenant_id, meta_schema_code(128), scope, field_key(128), keyword_value(128)),
    key idx_model_attr_index_tenant_number (tenant_id, meta_schema_code(128), scope, field_key(128), number_value)
);

create table if not exists workflow_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    code varchar(255),
    name varchar(255),
    current_version_id bigint,
    published int default 0,
    unique key uk_workflow_definition_project_code (project_id, code),
    unique key uk_workflow_definition_project_name (project_id, name),
    key idx_workflow_definition_project (project_id)
);

create table if not exists workflow_definition_version (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    definition_id bigint,
    version_number int,
    published int default 0,
    graph_json json,
    schedule_json json,
    key idx_workflow_definition_version_project (project_id)
);

create table if not exists workflow_node (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    workflow_version_id bigint,
    node_code varchar(255),
    node_name varchar(255),
    node_type varchar(128),
    config_json json,
    field_mappings_json json,
    key idx_workflow_node_project (project_id)
);

create table if not exists workflow_edge (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    workflow_version_id bigint,
    from_node_code varchar(255),
    to_node_code varchar(255),
    condition_type varchar(64),
    key idx_workflow_edge_project (project_id)
);

create table if not exists workflow_schedule (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    workflow_definition_id bigint,
    cron_expression varchar(255),
    enabled int default 0,
    timezone varchar(64),
    last_triggered_at datetime,
    key idx_workflow_schedule_project (project_id)
);

create table if not exists collection_task_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    name varchar(255),
    task_type varchar(64),
    status varchar(64),
    source_count int default 1,
    source_bindings_json json,
    target_binding_json json,
    field_mappings_json json,
    execution_options_json json,
    unique key uk_collection_task_definition_project_name (project_id, name),
    key idx_collection_task_definition_project (project_id)
);

create table if not exists collection_task_schedule (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    collection_task_id bigint,
    cron_expression varchar(255),
    enabled int default 0,
    timezone varchar(64),
    last_triggered_at datetime,
    key idx_collection_task_schedule_project (project_id)
);

create table if not exists quality_task_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    task_name varchar(255) not null,
    task_code varchar(255) not null,
    status varchar(64),
    rule_id bigint not null,
    rule_name_snapshot varchar(255),
    rule_dimension varchar(64),
    granularity varchar(32),
    datasource_id bigint,
    datasource_name_snapshot varchar(255),
    datasource_type_code varchar(128),
    model_id bigint,
    model_name_snapshot varchar(255),
    model_physical_locator varchar(500),
    column_name varchar(255),
    where_clause text,
    resolved_sql_preview text,
    parameter_bindings_json json,
    rule_snapshot_json json,
    unique key uk_quality_task_definition_project_code (project_id, task_code),
    unique key uk_quality_task_definition_project_name (project_id, task_name),
    key idx_quality_task_definition_project_status (project_id, status),
    key idx_quality_task_definition_rule_dimension (project_id, rule_dimension)
);

create table if not exists quality_task_schedule (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    quality_task_id bigint,
    cron_expression varchar(255),
    enabled int default 0,
    timezone varchar(64),
    last_triggered_at datetime,
    key idx_quality_task_schedule_project (project_id),
    key idx_quality_task_schedule_task (quality_task_id)
);

create table if not exists quality_task_alert (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    quality_task_id bigint not null,
    output_order int not null,
    result_field varchar(255) not null,
    output_type varchar(32) not null,
    enabled int default 0,
    operator varchar(32),
    expected_value varchar(255),
    min_value varchar(255),
    max_value varchar(255),
    key idx_quality_task_alert_task (quality_task_id),
    key idx_quality_task_alert_task_order (quality_task_id, output_order)
);

create table if not exists quality_issue (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    issue_code varchar(64),
    signature varchar(1024) not null,
    issue_type varchar(64),
    quality_task_id bigint,
    quality_task_name_snapshot varchar(255),
    rule_id bigint,
    rule_name_snapshot varchar(255),
    rule_dimension varchar(64),
    datasource_id bigint,
    datasource_name_snapshot varchar(255),
    datasource_type_code varchar(128),
    model_id bigint,
    model_name_snapshot varchar(255),
    model_physical_locator varchar(500),
    column_name varchar(255),
    output_field varchar(255),
    granularity varchar(32),
    title varchar(255),
    latest_message varchar(2000),
    severity varchar(32),
    system_severity varchar(32),
    manual_severity varchar(32),
    status varchar(32),
    assignee_user_id bigint,
    assignee_name_snapshot varchar(255),
    first_seen_at datetime,
    last_seen_at datetime,
    last_recovery_at datetime,
    sla_due_at datetime,
    occurrence_count int default 0,
    consecutive_failure_count int default 0,
    reopen_count int default 0,
    last_run_record_id bigint,
    last_run_status varchar(32),
    current_evidence_json json,
    unique key uk_quality_issue_signature (tenant_id, project_id, signature(255)),
    key idx_quality_issue_status_severity (project_id, status, severity),
    key idx_quality_issue_asset (project_id, datasource_id, model_id),
    key idx_quality_issue_task (project_id, quality_task_id),
    key idx_quality_issue_last_seen (project_id, last_seen_at)
);

create table if not exists quality_issue_comment (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    issue_id bigint not null,
    author_user_id bigint,
    author_name_snapshot varchar(255),
    content text,
    key idx_quality_issue_comment_issue (issue_id, created_at)
);

create table if not exists quality_issue_event (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    issue_id bigint not null,
    event_type varchar(64),
    event_title varchar(255),
    event_message text,
    actor_user_id bigint,
    actor_name_snapshot varchar(255),
    metadata_json json,
    key idx_quality_issue_event_issue (issue_id, created_at),
    key idx_quality_issue_event_project_type (project_id, event_type, created_at)
);

create table if not exists quality_metric_snapshot (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    snapshot_date date,
    datasource_id bigint,
    datasource_name_snapshot varchar(255),
    datasource_type_code varchar(128),
    model_id bigint,
    model_name_snapshot varchar(255),
    model_physical_locator varchar(500),
    rule_dimension varchar(64),
    execution_health_score bigint,
    governance_risk_score bigint,
    active_issue_count bigint,
    overdue_issue_count bigint,
    coverage_rate bigint,
    failure_rate bigint,
    affected_asset_count bigint,
    reopen_rate bigint,
    key idx_quality_metric_snapshot_project_date (project_id, snapshot_date),
    key idx_quality_metric_snapshot_asset (project_id, datasource_id, model_id, snapshot_date),
    key idx_quality_metric_snapshot_dimension (project_id, rule_dimension, snapshot_date)
);

create table if not exists data_service_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    service_code varchar(128) not null,
    service_name varchar(255) not null,
    service_type varchar(64) not null,
    status varchar(64) not null,
    source_type varchar(64) not null,
    datasource_id bigint,
    datasource_name_snapshot varchar(255),
    datasource_type_code varchar(128),
    model_id bigint,
    model_name_snapshot varchar(255),
    model_physical_locator varchar(1000),
    custom_sql longtext,
    request_method varchar(32),
    response_type varchar(32),
    endpoint_path varchar(1000),
    service_key varchar(128),
    cache_enabled int default 0,
    token_required int default 1,
    default_subscription_name varchar(255),
    webservice_enabled int default 0,
    webservice_config_json json,
    unique key uk_data_service_project_code (tenant_id, project_id, service_code),
    key idx_data_service_project_status (project_id, status),
    key idx_data_service_code_key (service_code, service_key)
);

create table if not exists data_service_request_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    sort_order int,
    param_name varchar(128) not null,
    field_name varchar(255),
    value_type varchar(64),
    query_operator varchar(64),
    required int default 0,
    description varchar(1000),
    fixed_param int default 0,
    key idx_data_service_request_service_order (service_id, sort_order)
);

create table if not exists data_service_response_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    sort_order int,
    enabled int default 1,
    param_name varchar(128) not null,
    field_name varchar(255) not null,
    example_value varchar(1000),
    description varchar(1000),
    transformers_json json,
    key idx_data_service_response_service_order (service_id, sort_order)
);

create table if not exists data_service_publish_param (
    id bigint primary key,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    sort_order int,
    frontend_param_name varchar(128) not null,
    backend_param_name varchar(128) not null,
    position varchar(32),
    value_type varchar(64),
    example_value varchar(1000),
    default_value varchar(1000),
    required int default 0,
    description varchar(1000),
    key idx_data_service_publish_service_order (service_id, sort_order)
);

create table if not exists data_service_subscription (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    subscription_name varchar(255) not null,
    token_hash varchar(128) not null,
    token_masked varchar(64),
    enabled int default 1,
    created_by bigint,
    last_used_at datetime,
    rotated_at datetime,
    rotated_by bigint,
    key idx_data_service_subscription_service_enabled (service_id, enabled),
    key idx_data_service_subscription_token (token_hash)
);

create table if not exists data_service_access_log (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint,
    service_code_snapshot varchar(255),
    service_name_snapshot varchar(255),
    service_status_snapshot varchar(64),
    subscription_id bigint,
    subscription_name_snapshot varchar(255),
    request_id varchar(128),
    request_method varchar(16),
    occurred_at datetime,
    duration_ms bigint,
    success int default 0,
    http_status int,
    error_code varchar(128),
    error_message varchar(1000),
    system_log mediumtext,
    client_ip varchar(128),
    user_agent varchar(500),
    cache_enabled int default 0,
    cache_hit int default 0,
    row_count bigint default 0,
    log_storage_type varchar(64),
    log_object_bucket varchar(255),
    log_object_key varchar(1000),
    log_size_bytes bigint,
    log_charset varchar(64),
    log_archive_status varchar(64),
    log_archive_error varchar(1000),
    key idx_data_service_access_project_time (tenant_id, project_id, occurred_at),
    key idx_data_service_access_service_time (service_id, occurred_at),
    key idx_data_service_access_subscription_time (subscription_id, occurred_at),
    key idx_data_service_access_success (project_id, success, occurred_at),
    key idx_data_service_access_cache (project_id, cache_hit, occurred_at)
);

create table if not exists data_service_access_counter (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null default 0,
    subscription_id bigint not null default 0,
    bucket_start datetime not null,
    success int not null default 0,
    cache_enabled int not null default 0,
    cache_hit int not null default 0,
    access_count bigint default 0,
    row_count bigint default 0,
    unique key uk_data_service_access_counter (tenant_id, project_id, service_id, subscription_id, bucket_start, success, cache_enabled, cache_hit),
    key idx_data_service_counter_project_bucket (tenant_id, project_id, bucket_start),
    key idx_data_service_counter_service_bucket (service_id, bucket_start)
);

create table if not exists data_ingestion_service (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    service_code varchar(128) not null,
    service_name varchar(255) not null,
    status varchar(64) not null,
    request_format varchar(32) not null,
    payload_mode varchar(32),
    data_node_path varchar(500),
    target_type varchar(32) not null,
    datasource_id bigint,
    datasource_name_snapshot varchar(255),
    datasource_type_code varchar(128),
    model_id bigint,
    model_name_snapshot varchar(255),
    model_physical_locator varchar(1000),
    endpoint_path varchar(1000),
    service_key varchar(128),
    max_batch_size int default 500,
    token_required int default 1,
    default_subscription_name varchar(255),
    webservice_enabled int default 0,
    webservice_config_json json,
    writer_options_json json,
    field_mappings_json json,
    unique key uk_data_ingestion_project_code (tenant_id, project_id, service_code),
    key idx_data_ingestion_project_status (project_id, status),
    key idx_data_ingestion_code_key (service_code, service_key)
);

create table if not exists data_ingestion_subscription (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    subscription_name varchar(255) not null,
    token_hash varchar(128) not null,
    token_masked varchar(64),
    enabled int default 1,
    created_by bigint,
    last_used_at datetime,
    rotated_at datetime,
    rotated_by bigint,
    key idx_data_ingestion_sub_service_enabled (service_id, enabled),
    key idx_data_ingestion_sub_token (token_hash)
);

create table if not exists data_ingestion_access_log (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint,
    service_code_snapshot varchar(255),
    service_name_snapshot varchar(255),
    service_status_snapshot varchar(64),
    subscription_id bigint,
    subscription_name_snapshot varchar(255),
    request_id varchar(128),
    request_method varchar(16),
    occurred_at datetime,
    duration_ms bigint,
    success int default 0,
    http_status int,
    error_code varchar(128),
    error_message varchar(1000),
    system_log mediumtext,
    client_ip varchar(128),
    user_agent varchar(500),
    received_count bigint default 0,
    success_count bigint default 0,
    failed_count bigint default 0,
    log_storage_type varchar(64),
    log_object_bucket varchar(255),
    log_object_key varchar(1000),
    log_size_bytes bigint,
    log_charset varchar(64),
    log_archive_status varchar(64),
    log_archive_error varchar(1000),
    key idx_data_ingestion_access_project_time (tenant_id, project_id, occurred_at),
    key idx_data_ingestion_access_service_time (service_id, occurred_at),
    key idx_data_ingestion_access_subscription_time (subscription_id, occurred_at),
    key idx_data_ingestion_access_success (project_id, success, occurred_at)
);

create table if not exists data_ingestion_access_counter (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null default 0,
    subscription_id bigint not null default 0,
    bucket_start datetime not null,
    success int not null default 0,
    access_count bigint default 0,
    received_count bigint default 0,
    success_count bigint default 0,
    failed_count bigint default 0,
    unique key uk_data_ingestion_access_counter (tenant_id, project_id, service_id, subscription_id, bucket_start, success),
    key idx_data_ingestion_counter_project_bucket (tenant_id, project_id, bucket_start),
    key idx_data_ingestion_counter_service_bucket (service_id, bucket_start)
);

create table if not exists protocol_conversion_service (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    service_code varchar(128) not null,
    service_name varchar(255) not null,
    status varchar(64) not null,
    endpoint_path varchar(1000),
    webservice_endpoint_path varchar(1000),
    service_key varchar(128),
    token_required int default 1,
    default_subscription_name varchar(255),
    source_protocol varchar(32) not null,
    source_method varchar(16),
    source_data_node_path varchar(500),
    webservice_config_json json,
    conversion_mode varchar(32) not null,
    field_mappings_json json,
    raw_transformers_json json,
    fixed_fields_json json,
    body_bridge_options_json json,
    request_passthrough_json json,
    target_datasource_id bigint,
    target_datasource_name_snapshot varchar(255),
    target_path varchar(1000),
    target_protocol varchar(32) not null,
    target_method varchar(16),
    target_headers_json json,
    target_query_json json,
    target_webservice_config_json json,
    target_body_template mediumtext,
    target_data_node_path varchar(500),
    payload_mode varchar(32),
    batch_size int default 1,
    response_status_json json,
    unique key uk_protocol_conversion_project_code (tenant_id, project_id, service_code),
    key idx_protocol_conversion_project_status (project_id, status),
    key idx_protocol_conversion_code_key (service_code, service_key)
);

create table if not exists protocol_conversion_subscription (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null,
    subscription_name varchar(255) not null,
    token_hash varchar(128) not null,
    token_masked varchar(64),
    enabled int default 1,
    created_by bigint,
    last_used_at datetime,
    rotated_at datetime,
    rotated_by bigint,
    key idx_protocol_conversion_sub_service_enabled (service_id, enabled),
    key idx_protocol_conversion_sub_token (token_hash)
);

create table if not exists protocol_conversion_access_log (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint,
    service_code_snapshot varchar(255),
    service_name_snapshot varchar(255),
    service_status_snapshot varchar(64),
    subscription_id bigint,
    subscription_name_snapshot varchar(255),
    request_id varchar(128),
    request_method varchar(16),
    source_protocol_snapshot varchar(32),
    target_protocol_snapshot varchar(32),
    occurred_at datetime,
    duration_ms bigint,
    success int default 0,
    http_status int,
    target_http_status int,
    error_code varchar(128),
    error_message varchar(1000),
    system_log mediumtext,
    client_ip varchar(128),
    user_agent varchar(500),
    received_count bigint default 0,
    success_count bigint default 0,
    failed_count bigint default 0,
    log_storage_type varchar(64),
    log_object_bucket varchar(255),
    log_object_key varchar(1000),
    log_size_bytes bigint,
    log_charset varchar(64),
    log_archive_status varchar(64),
    log_archive_error varchar(1000),
    key idx_protocol_conversion_access_project_time (tenant_id, project_id, occurred_at),
    key idx_protocol_conversion_access_service_time (service_id, occurred_at),
    key idx_protocol_conversion_access_subscription_time (subscription_id, occurred_at),
    key idx_protocol_conversion_access_success (project_id, success, occurred_at)
);

create table if not exists protocol_conversion_access_counter (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    service_id bigint not null default 0,
    subscription_id bigint not null default 0,
    bucket_start datetime not null,
    success int not null default 0,
    access_count bigint default 0,
    received_count bigint default 0,
    success_count bigint default 0,
    failed_count bigint default 0,
    unique key uk_protocol_conversion_access_counter (tenant_id, project_id, service_id, subscription_id, bucket_start, success),
    key idx_protocol_conversion_counter_project_bucket (tenant_id, project_id, bucket_start),
    key idx_protocol_conversion_counter_service_bucket (service_id, bucket_start)
);

create table if not exists data_dev_directory (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    parent_id bigint,
    name varchar(255),
    permission_code varchar(255),
    description varchar(1000),
    key idx_data_dev_directory_project_parent (project_id, parent_id),
    key idx_data_dev_directory_parent (parent_id)
);

create table if not exists data_dev_script (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    directory_id bigint,
    file_name varchar(255),
    script_type varchar(64),
    datasource_id bigint,
    description varchar(1000),
    content longtext,
    key idx_data_dev_script_project_directory (project_id, directory_id),
    key idx_data_dev_script_directory (directory_id),
    key idx_data_dev_script_datasource (datasource_id)
);

create table if not exists dispatch_task (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    execution_type varchar(64),
    workflow_run_id bigint,
    workflow_definition_id bigint,
    workflow_version_id bigint,
    collection_task_id bigint,
    triggered_by_user_id bigint,
    run_record_id bigint,
    node_code varchar(255),
    status varchar(64),
    worker_group_code varchar(255),
    lease_owner varchar(255),
    worker_instance_id varchar(255),
    lease_expires_at datetime,
    scheduled_fire_time datetime,
    attempts int default 0,
    max_retries int default 3,
    payload_json json,
    key idx_dispatch_task_project_status (project_id, status),
    key idx_dispatch_task_project_workflow_run (project_id, workflow_run_id),
    key idx_dispatch_task_project_status_created (project_id, status, created_at),
    key idx_dispatch_task_group_status_created (worker_group_code, status, created_at)
);

create table if not exists run_record (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    execution_type varchar(64),
    workflow_run_id bigint,
    workflow_definition_id bigint,
    workflow_version_id bigint,
    collection_task_id bigint,
    triggered_by_user_id bigint,
    node_code varchar(255),
    status varchar(64),
    worker_group_code varchar(255),
    worker_code varchar(255),
    worker_instance_id varchar(255),
    worker_pod_name varchar(255),
    worker_node_name varchar(255),
    message varchar(2000),
    started_at datetime,
    ended_at datetime,
    collected_records bigint,
    read_succeed_records bigint,
    read_failed_records bigint,
    write_succeed_records bigint,
    write_failed_records bigint,
    failed_records bigint,
    transformer_total_records bigint,
    transformer_success_records bigint,
    transformer_failed_records bigint,
    transformer_filter_records bigint,
    log_file_path varchar(1000),
    log_size_bytes bigint,
    log_charset varchar(64),
    log_storage_type varchar(64),
    log_object_bucket varchar(255),
    log_object_key varchar(1000),
    log_chunk_count int,
    log_status varchar(64),
    log_error_summary varchar(1000),
    payload_json json,
    result_json json,
    key idx_run_record_project_created (project_id, created_at),
    key idx_run_record_project_workflow_run (project_id, workflow_run_id),
    key idx_run_record_project_collection_task_ended (project_id, collection_task_id, ended_at)
);

create table if not exists data_model_lineage_relation (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    level varchar(32),
    source_type varchar(64),
    collection_task_id bigint,
    collection_task_name_snapshot varchar(255),
    source_datasource_id bigint,
    source_datasource_name_snapshot varchar(255),
    source_datasource_type_snapshot varchar(128),
    source_database_name_snapshot varchar(255),
    source_host_snapshot varchar(255),
    source_port_snapshot varchar(64),
    source_model_id bigint,
    source_model_name_snapshot varchar(255),
    source_model_locator_snapshot varchar(1000),
    source_field_key varchar(255),
    target_datasource_id bigint,
    target_datasource_name_snapshot varchar(255),
    target_datasource_type_snapshot varchar(128),
    target_database_name_snapshot varchar(255),
    target_host_snapshot varchar(255),
    target_port_snapshot varchar(64),
    target_model_id bigint,
    target_model_name_snapshot varchar(255),
    target_model_locator_snapshot varchar(1000),
    target_field_key varchar(255),
    mapping_mode varchar(64),
    expression_snapshot text,
    manual_maintainer_user_id bigint,
    manual_maintainer_name_snapshot varchar(255),
    latest_run_id bigint,
    latest_run_status varchar(64),
    latest_run_at datetime,
    key idx_data_model_lineage_target_level (tenant_id, target_model_id, level),
    key idx_data_model_lineage_source_level (tenant_id, source_model_id, level),
    key idx_data_model_lineage_task (tenant_id, collection_task_id),
    key idx_data_model_lineage_target_datasource_level (tenant_id, target_datasource_id, level),
    key idx_data_model_lineage_source_datasource_level (tenant_id, source_datasource_id, level)
);

create table if not exists worker_lease (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    worker_group_code varchar(255),
    worker_code varchar(255),
    worker_kind varchar(64),
    instance_id varchar(255),
    host_name varchar(255),
    pod_name varchar(255),
    node_name varchar(255),
    status varchar(64),
    last_heartbeat_at datetime,
    lease_expires_at datetime,
    capabilities_json json,
    key idx_worker_lease_code_instance (worker_code, instance_id),
    key idx_worker_lease_group_instance (worker_group_code, instance_id),
    key idx_worker_lease_status_heartbeat (status, last_heartbeat_at)
);

create table if not exists studio_cluster_lock (
    id bigint primary key,
    lock_name varchar(255) not null,
    owner_id varchar(255),
    locked_until datetime,
    last_acquired_at datetime,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    unique key uk_studio_cluster_lock_name (lock_name),
    key idx_studio_cluster_lock_until (locked_until)
);
