package com.jdragon.studio.infra.service;

import com.jdragon.studio.commons.exception.StudioException;
import com.jdragon.studio.dto.model.request.EnvironmentDependencyBatchDeleteRequest;
import com.jdragon.studio.dto.model.request.EnvironmentDependencySaveRequest;
import com.jdragon.studio.infra.entity.EnvironmentDependencyEntity;
import com.jdragon.studio.infra.entity.EnvironmentDependencyFileEntity;
import com.jdragon.studio.infra.mapper.EnvironmentDependencyFileMapper;
import com.jdragon.studio.infra.mapper.EnvironmentDependencyMapper;
import com.jdragon.studio.infra.mapper.ScriptEnvironmentDependencyRelMapper;
import com.jdragon.studio.infra.mapper.ScriptEnvironmentMapper;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.web.multipart.MultipartFile;

import java.util.Arrays;
import java.util.Collections;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class EnvironmentDependencyBatchExportTest {

    @Test
    void shouldExportLatestExactVersionsSortedByNormalizedName() {
        Fixture fixture = fixture();
        when(fixture.securityService.currentTenantId()).thenReturn("default");
        when(fixture.dependencyMapper.selectList(any())).thenReturn(Arrays.asList(
                pythonDependency(11L, "pandas", "2.3.3", 1L),
                pythonDependency(12L, "six", "1.17.0", 1L),
                pythonDependency(13L, "pandas", "2.2.0", 1L)));

        String manifest = fixture.service.exportPythonRequirements(null, true);

        assertEquals("# Generated by Data Aggregation Studio\n"
                + "# Exact Python package versions from the current package filter\n"
                + "pandas==2.3.3\n"
                + "six==1.17.0\n", manifest);
    }

    @Test
    void shouldDeleteLocalRecordsEvenWhenRepositoryDoesNotSupportDeletion() {
        Fixture fixture = fixture();
        EnvironmentDependencyEntity pandas = pythonDependency(21L, "pandas", "2.3.3", 31L);
        when(fixture.securityService.currentTenantId()).thenReturn("default");
        when(fixture.securityService.hasAnyRole(any(String[].class))).thenReturn(true);
        when(fixture.dependencyMapper.selectById(21L)).thenReturn(pandas);
        doThrow(new IllegalStateException("PYPISERVER deletion is not configured"))
                .when(fixture.artifactRepositoryPublisher)
                .validateArtifactVersionDeletion(31L, "PYTHON");
        doThrow(new IllegalStateException("PYPISERVER deletion is not configured"))
                .when(fixture.artifactRepositoryPublisher)
                .deleteArtifactVersion(eq(31L), eq("PYTHON"), eq("pandas"), eq("2.3.3"), any());
        when(fixture.dependencyFileMapper.selectList(any())).thenReturn(Collections.emptyList());
        EnvironmentDependencyBatchDeleteRequest request = new EnvironmentDependencyBatchDeleteRequest();
        request.setIds(Arrays.asList(21L, 21L, null));

        fixture.service.batchDelete(request);

        verify(fixture.dependencyMapper).deleteById(21L);
    }

    @Test
    void shouldPhysicallyClearSoftDeletedRowBeforeReUpload() {
        Fixture fixture = fixture();
        EnvironmentDependencyEntity deletedRow = pythonDependency(21L, "six", "1.17.0", 31L);
        deletedRow.setDeleted(1);
        when(fixture.securityService.currentTenantId()).thenReturn("default");
        when(fixture.securityService.hasAnyRole(any(String[].class))).thenReturn(true);
        when(fixture.dependencyMapper.selectByNameVersionIncludingDeleted("default", "six", "1.17.0"))
                .thenReturn(deletedRow);
        EnvironmentDependencyEntity existing = pythonDependency(99L, "six", "1.17.0", 31L);
        when(fixture.dependencyMapper.selectById(99L)).thenReturn(existing);
        when(fixture.dependencyFileMapper.selectList(any())).thenReturn(Collections.emptyList());

        // Multipart upload path: requireEntity(99) returns the existing row, then
        // ensureUniqueNameVersion finds the logically-deleted tombstone (id 21) occupying the
        // unique key and physically clears it so the re-upload can succeed.
        fixture.service.saveOrUpdateCheck(99L, "six", "1.17.0", "PYTHON", true, null,
                Collections.<MultipartFile>emptyList());

        verify(fixture.dependencyMapper).physicallyDeleteById(21L);
    }

    @Test
    void shouldAlwaysDownloadFromBoundRepositoryWithoutBackupLayer() {
        Fixture fixture = fixture();
        EnvironmentDependencyEntity dependency = pythonDependency(41L, "six", "1.17.0", 31L);
        EnvironmentDependencyFileEntity file = new EnvironmentDependencyFileEntity();
        file.setId(42L);
        file.setTenantId("default");
        file.setDependencyId(41L);
        file.setOriginalFileName("six-1.17.0-py2.py3-none-any.whl");
        file.setArtifactType("WHEEL");
        file.setObjectKey("legacy/backup/six.whl");
        file.setObjectUrl("oss://legacy-backup/legacy/backup/six.whl");
        file.setVisible(1);
        byte[] wheel = "wheel-content".getBytes(java.nio.charset.StandardCharsets.UTF_8);
        when(fixture.securityService.currentTenantId()).thenReturn("default");
        when(fixture.dependencyMapper.selectById(41L)).thenReturn(dependency);
        when(fixture.dependencyFileMapper.selectById(42L)).thenReturn(file);
        when(fixture.artifactRepositoryPublisher.downloadPackageFile(
                31L, "PYTHON", "six", "1.17.0", file.getOriginalFileName())).thenReturn(wheel);

        EnvironmentDependencyService.DependencyFileDownload download = fixture.service.downloadFile(41L, 42L);

        assertEquals(file.getOriginalFileName(), download.getFileName());
        assertArrayEquals(wheel, download.getBytes());
    }

    private Fixture fixture() {
        EnvironmentDependencyMapper dependencyMapper = mock(EnvironmentDependencyMapper.class);
        EnvironmentDependencyFileMapper dependencyFileMapper = mock(EnvironmentDependencyFileMapper.class);
        ScriptEnvironmentDependencyRelMapper relationMapper = mock(ScriptEnvironmentDependencyRelMapper.class);
        ScriptEnvironmentMapper environmentMapper = mock(ScriptEnvironmentMapper.class);
        StudioSecurityService securityService = mock(StudioSecurityService.class);
        @SuppressWarnings("unchecked")
        ObjectProvider<ScriptEnvironmentRuntimeService> runtimeServiceProvider = mock(ObjectProvider.class);
        ArtifactRepositoryPublisher artifactRepositoryPublisher = mock(ArtifactRepositoryPublisher.class);
        CloudObjectStorageService cloudObjectStorageService = mock(CloudObjectStorageService.class);
        PythonPackageDownloadCountService pythonPackageDownloadCountService = mock(PythonPackageDownloadCountService.class);
        EnvironmentDependencyService service = new EnvironmentDependencyService(
                dependencyMapper,
                dependencyFileMapper,
                relationMapper,
                environmentMapper,
                securityService,
                runtimeServiceProvider,
                cloudObjectStorageService,
                artifactRepositoryPublisher,
                pythonPackageDownloadCountService);
        return new Fixture(service, dependencyMapper, dependencyFileMapper, securityService,
                artifactRepositoryPublisher);
    }

    private EnvironmentDependencyEntity pythonDependency(Long id, String name, String version, Long storeId) {
        EnvironmentDependencyEntity entity = new EnvironmentDependencyEntity();
        entity.setId(id);
        entity.setTenantId("default");
        entity.setName(name);
        entity.setVersion(version);
        entity.setScriptType("PYTHON");
        entity.setArtifactStoreId(storeId);
        entity.setEnabled(1);
        return entity;
    }

    private static final class Fixture {
        private final EnvironmentDependencyService service;
        private final EnvironmentDependencyMapper dependencyMapper;
        private final EnvironmentDependencyFileMapper dependencyFileMapper;
        private final StudioSecurityService securityService;
        private final ArtifactRepositoryPublisher artifactRepositoryPublisher;

        private Fixture(EnvironmentDependencyService service,
                        EnvironmentDependencyMapper dependencyMapper,
                        EnvironmentDependencyFileMapper dependencyFileMapper,
                        StudioSecurityService securityService,
                        ArtifactRepositoryPublisher artifactRepositoryPublisher) {
            this.service = service;
            this.dependencyMapper = dependencyMapper;
            this.dependencyFileMapper = dependencyFileMapper;
            this.securityService = securityService;
            this.artifactRepositoryPublisher = artifactRepositoryPublisher;
        }
    }
}
