-- Studio unstructured file transfer task, run, item and metric persistence.

alter table dispatch_task
    add column file_transfer_task_id bigint after quality_task_id,
    add column file_transfer_run_id bigint after file_transfer_task_id,
    add index idx_dispatch_task_file_transfer_run (file_transfer_run_id, status);

alter table run_record
    add column file_transfer_task_id bigint after quality_task_id,
    add column file_transfer_run_id bigint after file_transfer_task_id,
    add index idx_run_record_file_transfer_run (file_transfer_run_id);

create table file_transfer_task_definition (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    created_by bigint,
    name varchar(255) not null,
    code varchar(128) not null,
    status varchar(32) not null,
    version int not null default 1,
    published_version int,
    source_runtime_cluster_id bigint not null,
    source_datasource_id bigint not null,
    source_datasource_name_snapshot varchar(255),
    source_datasource_type_snapshot varchar(128),
    target_runtime_cluster_id bigint not null,
    target_datasource_id bigint not null,
    target_datasource_name_snapshot varchar(255),
    target_datasource_type_snapshot varchar(128),
    selection_json json,
    mapping_json json,
    policy_json json,
    runtime_json json,
    published_snapshot_json json,
    schedule_enabled int default 0,
    cron_expression varchar(255),
    timezone varchar(64),
    last_triggered_at datetime,
    unique key uk_ft_task_project_code (tenant_id, project_id, code),
    key idx_ft_task_project_status (project_id, status),
    key idx_ft_task_schedule (status, schedule_enabled, last_triggered_at)
);

create table file_transfer_run (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    run_record_id bigint,
    task_id bigint,
    task_name_snapshot varchar(255),
    trigger_type varchar(32),
    direction varchar(32),
    channel varchar(32),
    status varchar(32) not null,
    source_runtime_cluster_id bigint,
    source_datasource_id bigint,
    target_runtime_cluster_id bigint not null,
    target_datasource_id bigint,
    total_files bigint default 0,
    success_files bigint default 0,
    skipped_files bigint default 0,
    failed_files bigint default 0,
    conflict_files bigint default 0,
    resumed_files bigint default 0,
    post_action_failed_files bigint default 0,
    total_bytes bigint default 0,
    transferred_bytes bigint default 0,
    failed_bytes bigint default 0,
    resumed_bytes bigint default 0,
    current_bytes_per_second bigint default 0,
    peak_bytes_per_second bigint default 0,
    active_files int default 0,
    retry_count int default 0,
    message varchar(2000),
    started_at datetime,
    ended_at datetime,
    resolved_spec_json json,
    unique key uk_ft_run_record (run_record_id),
    key idx_ft_run_project_created (project_id, created_at),
    key idx_ft_run_task_status (task_id, status),
    key idx_ft_run_target_status (target_runtime_cluster_id, status)
);

create table file_transfer_run_item (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    run_id bigint not null,
    core_item_id varchar(64) not null,
    direction varchar(32),
    channel varchar(32),
    source_runtime_cluster_id bigint not null,
    source_datasource_id bigint not null,
    source_path varchar(2000) not null,
    target_runtime_cluster_id bigint not null,
    target_datasource_id bigint not null,
    target_path varchar(2000) not null,
    temporary_path varchar(2000),
    status varchar(32) not null,
    file_size bigint default 0,
    transferred_bytes bigint default 0,
    resumed_bytes bigint default 0,
    current_bytes_per_second bigint default 0,
    source_checksum varchar(128),
    target_checksum varchar(128),
    attempts int default 0,
    error_code varchar(128),
    error_message varchar(2000),
    conflict_action varchar(32),
    source_action varchar(32),
    post_action_status varchar(32),
    started_at datetime,
    ended_at datetime,
    source_snapshot_json json,
    checkpoint_json json,
    unique key uk_ft_item_run_core (run_id, core_item_id),
    key idx_ft_item_run_status (run_id, status),
    key idx_ft_item_project_updated (project_id, updated_at)
);

create table file_transfer_metric_sample (
    id bigint primary key,
    tenant_id varchar(64) default 'default',
    project_id bigint,
    deleted int default 0,
    created_at datetime default current_timestamp,
    updated_at datetime default current_timestamp,
    run_id bigint not null,
    run_record_id bigint,
    task_id bigint,
    runtime_cluster_id bigint,
    source_datasource_id bigint,
    target_datasource_id bigint,
    channel varchar(32),
    status varchar(32),
    sampled_at datetime not null,
    transferred_bytes bigint default 0,
    bytes_per_second bigint default 0,
    completed_files bigint default 0,
    failed_files bigint default 0,
    active_files int default 0,
    retry_count int default 0,
    key idx_ft_metric_project_time (project_id, sampled_at),
    key idx_ft_metric_run_time (run_id, sampled_at),
    key idx_ft_metric_task_time (task_id, sampled_at)
);
