export const STUDIO_RUN_STATUS = {
  DRAFT: "DRAFT",
  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
  PUBLISHED: "PUBLISHED",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  ERROR: "ERROR",
  RUNNING: "RUNNING",
  PENDING: "PENDING",
  QUEUED: "QUEUED",
  STOPPING: "STOPPING",
  STOPPED: "STOPPED",
  NOT_RUN: "NOT_RUN",
  UNKNOWN: "UNKNOWN",
} as const;

export const STUDIO_RESOURCE_TYPE = {
  COLLECTION_TASK: "COLLECTION_TASK",
  COLLECTION_TASK_RUN: "COLLECTION_TASK_RUN",
  QUALITY_TASK: "QUALITY_TASK",
  WORKFLOW: "WORKFLOW",
  WORKFLOW_RUN: "WORKFLOW_RUN",
  DATASOURCE: "DATASOURCE",
  DATA_MODEL: "DATA_MODEL",
  MODEL_SYNC_TASK: "MODEL_SYNC_TASK",
} as const;

export const STUDIO_NODE_TYPE = {
  COLLECTION_TASK: "COLLECTION_TASK",
  QUALITY_TASK: "QUALITY_TASK",
  FILE_TRANSFER: "FILE_TRANSFER",
  DATA_SCRIPT: "DATA_SCRIPT",
  ETL_SINGLE: "ETL_SINGLE",
  FUSION: "FUSION",
  CONSISTENCY: "CONSISTENCY",
  HTTP: "HTTP",
  SHELL: "SHELL",
} as const;

export const STUDIO_DATASOURCE_CATEGORY = {
  DATABASE: "DATABASE",
  FILE_SYSTEM: "FILE_SYSTEM",
  MESSAGE_QUEUE: "MESSAGE_QUEUE",
  HTTP_API: "HTTP_API",
} as const;

export const RUNNING_STATUSES = new Set<string>([
  STUDIO_RUN_STATUS.RUNNING,
  STUDIO_RUN_STATUS.QUEUED,
  STUDIO_RUN_STATUS.PENDING,
  STUDIO_RUN_STATUS.STOPPING,
]);

export const TERMINAL_STATUSES = new Set<string>([
  STUDIO_RUN_STATUS.SUCCESS,
  STUDIO_RUN_STATUS.FAILED,
  STUDIO_RUN_STATUS.ERROR,
  STUDIO_RUN_STATUS.STOPPED,
]);

export type StudioRunStatus = typeof STUDIO_RUN_STATUS[keyof typeof STUDIO_RUN_STATUS];
export type StudioResourceType = typeof STUDIO_RESOURCE_TYPE[keyof typeof STUDIO_RESOURCE_TYPE];
export type StudioNodeType = typeof STUDIO_NODE_TYPE[keyof typeof STUDIO_NODE_TYPE];
export type StudioDatasourceCategory = typeof STUDIO_DATASOURCE_CATEGORY[keyof typeof STUDIO_DATASOURCE_CATEGORY];
